In [1]:
from Pipeline.Global.GallstoneDataSet import GallstoneDataSet
from Pipeline.Methodology.EvaluationELM import EvaluationELM
from Pipeline.Global.GlobalSetting import GlobalSetting

In [2]:
gallstone_dataset = GallstoneDataSet()
gallstone_dataset.fetch_data_path_1()

features_size = gallstone_dataset.x_train.shape[1]

In [3]:
# 1. Instantiate the Evaluator Object ONCE
evaluator = EvaluationELM(
    x_train = gallstone_dataset.x_train,
    y_train = gallstone_dataset.y_train,
    activation_function     = GlobalSetting.sigmoid ,
    elm_init_seed_range     = GlobalSetting.elm_initial_state_range ,
    k_fold = 5
)

In [4]:
hidden_size_record ,hidden_size_result = evaluator.grid_search_hidden_size(
    GlobalSetting.hidden_size_explore_range
)
GlobalSetting.save_dataframe_to_record(hidden_size_record,'hidden_size_record.csv')
hidden_node_list = EvaluationELM.extract_top_results(hidden_size_result)
best_hidden_size = hidden_node_list.iloc[0]
hidden_size_record

Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 161
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 162
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 163
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 164
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 165
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 166
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 167
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 168
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 169
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 170
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 171
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 172
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 173
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 174
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 175
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 176
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 177
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 178
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 179
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 180
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 181
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 182
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 183
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 184
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 185
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 186
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 187
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 188
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 189
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 190
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 161
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 162
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 163
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 164
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 165
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 166
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 167
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 168
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 169
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 170
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 171
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 172
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 173
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 174
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 175
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 176
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 177
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 178
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 179
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 180
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 181
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 182
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 183
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 184
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 185
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 186
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 187
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 188
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 189
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 190
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 161
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 162
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 163
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 164
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 165
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 166
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 167
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 168
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 169
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 170
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 171
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 172
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 173
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 174
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 175
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 176
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 177
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 178
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 179
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 180
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 181
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 182
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 183
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 184
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 185
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 186
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 187
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 188
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 189
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 190
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 161
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 162
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 163
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 164
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 165
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 166
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 167
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 168
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 169
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 170
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 171
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 172
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 173
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 174
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 175
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 176
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 177
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 178
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 179
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 180
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 181
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 182
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 183
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 184
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 185
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 186
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 187
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 188
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 189
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 190
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 161
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 162
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 163
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 164
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 165
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 166
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 167
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 168
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 169
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 170
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 171
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 172
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 173
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 174
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 175
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 176
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 177
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 178
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 179
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 180
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 181
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 182
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 183
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 184
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 185
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 186
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 187
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 188
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 189
Running -> Nodes: 1   | Lambda: 0.0000000000 | Fold: 5 /5  | ELM Seed: 190
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 161
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 162
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 163
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 164
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 165
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 166
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 167
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 168
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 169
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 170
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 171
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 172
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 173
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 174
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 175
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 176
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 177
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 178
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 179
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 180
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 181
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 182
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 183
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 184
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 185
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 186
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 187
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 188
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 189
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 1 /5  | ELM Seed: 190
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 161
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 162
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 163
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 164
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 165
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 166
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 167
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 168
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 169
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 170
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 171
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 172
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 173
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 174
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 175
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 176
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 177
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 178
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 179
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 180
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 181
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 182
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 183
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 184
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 185
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 186
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 187
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 188
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 189
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 2 /5  | ELM Seed: 190
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 161
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 162
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 163
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 164
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 165
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 166
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 167
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 168
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 169
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 170
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 171
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 172
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 173
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 174
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 175
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 176
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 177
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 178
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 179
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 180
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 181
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 182
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 183
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 184
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 185
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 186
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 187
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 188
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 189
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 3 /5  | ELM Seed: 190
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 161
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 162
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 163
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 164
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 165
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 166
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 167
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 168
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 169
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 170
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 171
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 172
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 173
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 174
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 175
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 176
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 177
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 178
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 179
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 180
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 181
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 182
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 183
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 184
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 185
Running -> Nodes: 2   | Lambda: 0.0000000000 | Fold: 4 /5  | ELM Seed: 186

,Hidden_Nodes,Activation,Lambda_Value,Fold,ELM_Seed,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
0,1,sigmoid,0.0,0,161,0.490196,0.000000,0.00,0.490196,1.000000,0.000000,0.000000,0.500000,0.000000
1,1,sigmoid,0.0,0,162,0.490196,0.000000,0.00,0.490196,1.000000,0.000000,0.000000,0.500000,0.000000
2,1,sigmoid,0.0,0,163,0.490196,0.000000,0.00,0.490196,1.000000,0.000000,0.000000,0.500000,0.000000
3,1,sigmoid,0.0,0,164,0.490196,0.000000,0.00,0.490196,1.000000,0.000000,0.000000,0.500000,0.000000
4,1,sigmoid,0.0,0,165,0.490196,0.000000,0.00,0.490196,1.000000,0.000000,0.000000,0.500000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,100,sigmoid,0.0,4,186,0.745098,0.730769,0.76,0.760000,0.730769,0.745098,0.753968,0.745385,0.490769
14996,100,sigmoid,0.0,4,187,0.784314,0.818182,0.72,0.758621,0.846154,0.765957,0.737705,0.783077,0.571453
14997,100,sigmoid,0.0,4,188,0.784314,0.769231,0.80,0.800000,0.769231,0.784314,0.793651,0.784615,0.569231
14998,100,sigmoid,0.0,4,189,0.627451,0.625000,0.60,0.629630,0.653846,0.612245,0.604839,0.626923,0.254238
14999,100,sigmoid,0.0,4,190,0.764706,0.782609,0.72,0.750000,0.807692,0.750000,0.731707,0.763846,0.530145

In [5]:
hidden_size_result

,Hidden_Nodes,Activation,Lambda_Value,avg_Accuracy_Seed_Mean,avg_Accuracy_Seed_Std,avg_Accuracy_Seed_SEM,avg_Accuracy_Seed_Min,avg_Accuracy_Seed_Max,avg_Precision_Seed_Mean,avg_Precision_Seed_Std,...,avg_Bal Accuracy_Seed_Mean,avg_Bal Accuracy_Seed_Std,avg_Bal Accuracy_Seed_SEM,avg_Bal Accuracy_Seed_Min,avg_Bal Accuracy_Seed_Max,avg_MCC_Seed_Mean,avg_MCC_Seed_Std,avg_MCC_Seed_SEM,avg_MCC_Seed_Min,avg_MCC_Seed_Max
0,1,sigmoid,0.0,0.505882,0.000000,0.000000,0.505882,0.505882,0.000000,0.000000,...,0.500000,0.000000,0.000000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2,sigmoid,0.0,0.540915,0.044019,0.008037,0.447059,0.643137,0.511037,0.104700,...,0.540051,0.044518,0.008128,0.446000,0.641846,0.082647,0.091076,0.016628,-0.111021,0.290719
2,3,sigmoid,0.0,0.547974,0.041129,0.007509,0.470588,0.623529,0.546477,0.057269,...,0.547492,0.040970,0.007480,0.471231,0.622000,0.096310,0.085181,0.015552,-0.058379,0.256095
3,4,sigmoid,0.0,0.574248,0.036435,0.006652,0.490196,0.627451,0.577199,0.042242,...,0.573913,0.036310,0.006629,0.490462,0.627385,0.151162,0.073027,0.013333,-0.018850,0.256528
4,5,sigmoid,0.0,0.602222,0.040107,0.007323,0.552941,0.698039,0.609420,0.046069,...,0.601862,0.040093,0.007320,0.551846,0.697692,0.207173,0.081075,0.014802,0.105919,0.402328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,sigmoid,0.0,0.684314,0.025094,0.004582,0.643137,0.737255,0.703528,0.024181,...,0.683713,0.025308,0.004621,0.642615,0.737538,0.372824,0.049883,0.009107,0.288362,0.478896
96,97,sigmoid,0.0,0.682353,0.025911,0.004731,0.623529,0.729412,0.702798,0.028664,...,0.681764,0.025850,0.004720,0.623385,0.729077,0.369570,0.052259,0.009541,0.254258,0.468831
97,98,sigmoid,0.0,0.681046,0.029171,0.005326,0.611765,0.741176,0.703912,0.033428,...,0.680421,0.029506,0.005387,0.610308,0.741538,0.368211,0.059692,0.010898,0.225723,0.486277
98,99,sigmoid,0.0,0.689804,0.026162,0.004777,0.635294,0.725490,0.709709,0.029993,...,0.689185,0.026318,0.004805,0.634615,0.724923,0.384761,0.053138,0.009702,0.276325,0.459930
99,100,sigmoid,0.0,0.684314,0.025137,0.004589,0.643137,0.729412,0.704415,0.028645,...,0.683538,0.025215,0.004604,0.641846,0.728769,0.372909,0.050092,0.009146,0.292222,0.465975

In [6]:
lambda_record, lambda_result = evaluator.grid_search_lambda(
    hidden_size     = best_hidden_size['Hidden_Nodes'],
    lambda_range    = GlobalSetting.lambda_value_explore_range
)
GlobalSetting.save_dataframe_to_record(lambda_record,'lambda_record.csv')
lambda_value_list = EvaluationELM.extract_top_results(lambda_result)
best_lambda_value = lambda_value_list.iloc[0]

Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 186

In [7]:
size_lambda_record , size_lambda_result = evaluator.grid_search_hidden_size_and_lambda(
    hidden_size_range   = hidden_node_list['Hidden_Nodes'],
    lambda_range        = GlobalSetting.lambda_value_explore_range
)
GlobalSetting.save_dataframe_to_record(size_lambda_record,'size_lambda_record.csv')
size_lambda_list = EvaluationELM.extract_top_results(size_lambda_result)
best_size_lambda = size_lambda_list.iloc[0]

Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 1 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 2 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 3 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 4 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000298 | Fold: 5 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 1 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 2 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 186
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 187
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 188
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 189
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 3 /5  | ELM Seed: 190
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 161
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 162
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 163
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 164
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 165
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 166
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 167
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 168
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 169
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 170
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 171
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 172
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 173
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 174
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 175
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 176
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 177
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 178
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 179
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 180
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 181
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 182
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 183
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 184
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 185
Running -> Nodes: 48  | Lambda: 0.0000000596 | Fold: 4 /5  | ELM Seed: 186

In [8]:
model_configs_payload = [
    {
        "Model_Types" : "Best_Hidden_Nodes",
        "Hidden_Nodes": int(best_hidden_size['Hidden_Nodes']),
        "Activation": "sigmoid",
        "Lambda_Value": float(best_hidden_size['Lambda_Value'])
    },
    {
        "Model_Types" : "Best_Lambda",
        "Hidden_Nodes": int(best_lambda_value['Hidden_Nodes']),
        "Activation": "sigmoid",
        "Lambda_Value": float(best_lambda_value['Lambda_Value'])
    },
    {
        "Model_Types" : "Best_Size_and_Lambda",
        "Hidden_Nodes": int(best_size_lambda['Hidden_Nodes']),
        "Activation": "sigmoid",
        "Lambda_Value": float(best_size_lambda['Lambda_Value'])
    }
]
GlobalSetting.upsert_model_configs(model_configs_payload)

In [9]:
best_size_lambda

Hidden_Nodes                        48
Activation                     sigmoid
Lambda_Value                  0.007812
avg_Accuracy_Seed_Mean        0.734902
avg_Accuracy_Seed_Std         0.018583
avg_Accuracy_Seed_SEM         0.003393
avg_Accuracy_Seed_Min         0.678431
avg_Accuracy_Seed_Max         0.768627
avg_Precision_Seed_Mean       0.773611
avg_Precision_Seed_Std        0.025163
avg_Precision_Seed_SEM        0.004594
avg_Precision_Seed_Min        0.704273
avg_Precision_Seed_Max        0.816957
avg_Recall_Seed_Mean          0.661569
avg_Recall_Seed_Std           0.025798
avg_Recall_Seed_SEM            0.00471
avg_Recall_Seed_Min           0.619077
avg_Recall_Seed_Max           0.715385
avg_NPV_Seed_Mean             0.710783
avg_NPV_Seed_Std              0.017814
avg_NPV_Seed_SEM              0.003252
avg_NPV_Seed_Min              0.663936
avg_NPV_Seed_Max              0.737868
avg_Specificity_Seed_Mean     0.806759
avg_Specificity_Seed_Std      0.027127
avg_Specificity_Seed_SEM      0.004953
avg_Specificity_Seed_Min      0.736308
avg_Specificity_Seed_Max      0.853231
avg_F1-Score_Seed_Mean        0.710706
avg_F1-Score_Seed_Std          0.02043
avg_F1-Score_Seed_SEM          0.00373
avg_F1-Score_Seed_Min         0.656125
avg_F1-Score_Seed_Max         0.746702
avg_F2-Score_Seed_Mean         0.67992
avg_F2-Score_Seed_Std         0.023156
avg_F2-Score_Seed_SEM         0.004228
avg_F2-Score_Seed_Min         0.633105
avg_F2-Score_Seed_Max          0.72089
avg_Bal Accuracy_Seed_Mean    0.734164
avg_Bal Accuracy_Seed_Std     0.018664
avg_Bal Accuracy_Seed_SEM     0.003407
avg_Bal Accuracy_Seed_Min        0.678
avg_Bal Accuracy_Seed_Max     0.768154
avg_MCC_Seed_Mean             0.476215
avg_MCC_Seed_Std              0.037735
avg_MCC_Seed_SEM              0.006889
avg_MCC_Seed_Min              0.362019
avg_MCC_Seed_Max              0.544329
rank_score                    0.706976
Name: 18, dtype: object