In [1]:
import numpy as np
import pandas as pd
#
# from DataSplit import DataSplit
# from ExtremeLearningMachine import ExtremeLearningMachine
# from EvaluationMatrix import EvaluationMatrix
from Pipeline.Model.EvaluationELM import EvaluationELM

In [2]:
filePath = '../../Dataset/UCI_Gallstone_Dataset.csv'
df = pd.read_csv(filePath)

targetCol = ['Gallstone Status']
X = df.drop(targetCol, axis=1)
y = df[targetCol]

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [4]:
hidden_size_explore = range(40, 61)
lambda_value_explore = np.arange(7.00, 9.00, 0.25)

In [6]:
hs_result = EvaluationELM.grid_search_hidden_size(X, y, sigmoid, hidden_size_explore)
hs_result

Hidden Node Size: 40
Hidden Node Size: 41
Hidden Node Size: 42
Hidden Node Size: 43
Hidden Node Size: 44
Hidden Node Size: 45
Hidden Node Size: 46
Hidden Node Size: 47
Hidden Node Size: 48
Hidden Node Size: 49
Hidden Node Size: 50
Hidden Node Size: 51
Hidden Node Size: 52
Hidden Node Size: 53
Hidden Node Size: 54
Hidden Node Size: 55
Hidden Node Size: 56
Hidden Node Size: 57
Hidden Node Size: 58
Hidden Node Size: 59
Hidden Node Size: 60

,Hidden_Nodes,Activation,Lambda Value,avg_Accuracy_Seed_Mean,avg_Accuracy_Seed_Std,avg_Accuracy_Seed_Min,avg_Accuracy_Seed_Max,avg_Precision_Seed_Mean,avg_Precision_Seed_Std,avg_Precision_Seed_Min,...,avg_F1-Score_Seed_Min,avg_F1-Score_Seed_Max,avg_Balanced Accuracy_Seed_Mean,avg_Balanced Accuracy_Seed_Std,avg_Balanced Accuracy_Seed_Min,avg_Balanced Accuracy_Seed_Max,avg_MCC_Seed_Mean,avg_MCC_Seed_Std,avg_MCC_Seed_Min,avg_MCC_Seed_Max
0,40,sigmoid,0.0,0.6751,0.0230,0.6392,0.7176,0.6930,0.0332,0.6513,...,0.5971,0.6937,0.6748,0.0229,0.6385,0.7172,0.3544,0.0469,0.2813,0.4437
1,41,sigmoid,0.0,0.6702,0.0257,0.6196,0.7255,0.6894,0.0348,0.6336,...,0.5701,0.7067,0.6698,0.0258,0.6180,0.7252,0.3452,0.0535,0.2430,0.4654
2,42,sigmoid,0.0,0.6627,0.0241,0.6118,0.7059,0.6787,0.0300,0.6197,...,0.5816,0.6968,0.6623,0.0243,0.6103,0.7060,0.3300,0.0501,0.2245,0.4267
3,43,sigmoid,0.0,0.6641,0.0352,0.6078,0.7255,0.6793,0.0414,0.6094,...,0.5836,0.7030,0.6639,0.0351,0.6083,0.7254,0.3329,0.0703,0.2190,0.4599
4,44,sigmoid,0.0,0.6616,0.0296,0.6039,0.7137,0.6769,0.0332,0.6064,...,0.5807,0.6964,0.6613,0.0296,0.6035,0.7140,0.3279,0.0600,0.2079,0.4317
5,45,sigmoid,0.0,0.6749,0.0285,0.6196,0.7490,0.6917,0.0360,0.6276,...,0.5927,0.7308,0.6743,0.0285,0.6177,0.7483,0.3533,0.0578,0.2426,0.5055
6,46,sigmoid,0.0,0.6713,0.0244,0.6314,0.7255,0.6863,0.0269,0.6397,...,0.6142,0.7218,0.6708,0.0244,0.6305,0.7254,0.3463,0.0493,0.2656,0.4519
7,47,sigmoid,0.0,0.6629,0.0359,0.6078,0.7490,0.6779,0.0415,0.6086,...,0.5927,0.7336,0.6624,0.0358,0.6074,0.7480,0.3290,0.0729,0.2176,0.5050
8,48,sigmoid,0.0,0.6684,0.0288,0.6157,0.7137,0.6851,0.0333,0.6168,...,0.5903,0.6954,0.6678,0.0287,0.6155,0.7137,0.3402,0.0574,0.2330,0.4324
9,49,sigmoid,0.0,0.6812,0.0338,0.6000,0.7490,0.6974,0.0399,0.6098,...,0.5672,0.7360,0.6808,0.0337,0.5989,0.7486,0.3659,0.0683,0.2003,0.5014
10,50,sigmoid,0.0,0.6784,0.0296,0.6039,0.7216,0.6911,0.0340,0.6157,...,0.5882,0.7080,0.6782,0.0294,0.6043,0.7208,0.3605,0.0595,0.2126,0.4462
11,51,sigmoid,0.0,0.6635,0.0250,0.6196,0.7098,0.6777,0.0317,0.6277,...,0.5979,0.7022,0.6632,0.0249,0.6195,0.7085,0.3316,0.0503,0.2407,0.4248
12,52,sigmoid,0.0,0.6730,0.0317,0.6078,0.7373,0.6908,0.0388,0.6224,...,0.5736,0.7075,0.6724,0.0315,0.6075,0.7363,0.3497,0.0632,0.2199,0.4813
13,53,sigmoid,0.0,0.6736,0.0249,0.6118,0.7137,0.6920,0.0346,0.6197,...,0.5931,0.7016,0.6730,0.0249,0.6115,0.7129,0.3514,0.0516,0.2255,0.4302
14,54,sigmoid,0.0,0.6654,0.0193,0.6235,0.6941,0.6848,0.0231,0.6353,...,0.5912,0.6780,0.6650,0.0194,0.6229,0.6937,0.3350,0.0395,0.2483,0.3928
15,55,sigmoid,0.0,0.6674,0.0250,0.6157,0.7294,0.6807,0.0303,0.6205,...,0.5968,0.7216,0.6671,0.0250,0.6157,0.7292,0.3385,0.0514,0.2338,0.4613
16,56,sigmoid,0.0,0.6743,0.0398,0.5725,0.7294,0.6895,0.0463,0.5939,...,0.5478,0.7216,0.6742,0.0399,0.5720,0.7294,0.3530,0.0803,0.1523,0.4606
17,57,sigmoid,0.0,0.6697,0.0279,0.6314,0.7255,0.6816,0.0330,0.6349,...,0.6028,0.7176,0.6694,0.0281,0.6306,0.7255,0.3427,0.0570,0.2639,0.4520
18,58,sigmoid,0.0,0.6781,0.0414,0.5765,0.7412,0.6939,0.0437,0.5796,...,0.5593,0.7345,0.6776,0.0415,0.5758,0.7405,0.3597,0.0832,0.1545,0.4861
19,59,sigmoid,0.0,0.6721,0.0315,0.6196,0.7529,0.6871,0.0335,0.6369,...,0.5880,0.7416,0.6716,0.0316,0.6180,0.7528,0.3480,0.0632,0.2421,0.5075
20,60,sigmoid,0.0,0.6775,0.0282,0.6275,0.7333,0.6970,0.0313,0.6417,...,0.6017,0.7237,0.6769,0.0282,0.6260,0.7332,0.3595,0.0559,0.2597,0.4697

In [8]:
hidden_size = hs_result.sort_values(by='avg_Accuracy_Seed_Mean',ascending=False).iloc[0]['Hidden_Nodes']
hidden_size

np.int64(49)

In [9]:
lb_result = EvaluationELM.grid_search_lambda(X,y,sigmoid,hidden_size,lambda_value_explore)
lb_result

Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75

,Hidden_Nodes,Activation,Lambda Value,avg_Accuracy_Seed_Mean,avg_Accuracy_Seed_Std,avg_Accuracy_Seed_Min,avg_Accuracy_Seed_Max,avg_Precision_Seed_Mean,avg_Precision_Seed_Std,avg_Precision_Seed_Min,...,avg_F1-Score_Seed_Min,avg_F1-Score_Seed_Max,avg_Balanced Accuracy_Seed_Mean,avg_Balanced Accuracy_Seed_Std,avg_Balanced Accuracy_Seed_Min,avg_Balanced Accuracy_Seed_Max,avg_MCC_Seed_Mean,avg_MCC_Seed_Std,avg_MCC_Seed_Min,avg_MCC_Seed_Max
0,49,sigmoid,7.00,0.6896,0.0332,0.6275,0.7647,0.7153,0.0411,0.6570,...,0.6007,0.7474,0.6891,0.0330,0.6272,0.7638,0.3843,0.0670,0.2627,0.5378
1,49,sigmoid,7.25,0.6898,0.0334,0.6275,0.7647,0.7156,0.0413,0.6570,...,0.6007,0.7474,0.6893,0.0332,0.6272,0.7638,0.3846,0.0674,0.2627,0.5378
2,49,sigmoid,7.50,0.6896,0.0332,0.6275,0.7647,0.7153,0.0409,0.6570,...,0.6007,0.7474,0.6891,0.0330,0.6272,0.7638,0.3843,0.0670,0.2627,0.5378
3,49,sigmoid,7.75,0.6900,0.0313,0.6392,0.7647,0.7159,0.0389,0.6672,...,0.6109,0.7474,0.6895,0.0311,0.6389,0.7638,0.3851,0.0630,0.2877,0.5378
4,49,sigmoid,8.00,0.6898,0.0310,0.6392,0.7647,0.7161,0.0387,0.6672,...,0.6109,0.7474,0.6893,0.0308,0.6389,0.7638,0.3849,0.0626,0.2877,0.5378
5,49,sigmoid,8.25,0.6900,0.0313,0.6392,0.7647,0.7165,0.0390,0.6672,...,0.6109,0.7474,0.6894,0.0311,0.6389,0.7638,0.3853,0.0631,0.2877,0.5378
6,49,sigmoid,8.50,0.6883,0.0305,0.6353,0.7608,0.7151,0.0384,0.6672,...,0.6045,0.7410,0.6878,0.0303,0.6351,0.7598,0.3821,0.0617,0.2803,0.5313
7,49,sigmoid,8.75,0.6876,0.0311,0.6314,0.7569,0.7143,0.0391,0.6604,...,0.6014,0.7354,0.6870,0.0309,0.6312,0.7558,0.3805,0.0628,0.2710,0.5234

In [10]:
db_result = EvaluationELM.grid_search_hidden_size_and_lambda(X,y,sigmoid,hidden_size_explore,lambda_value_explore)
db_result

Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75
Lambda Value: 7.0
Lambda Value: 7.25
Lambda Value: 7.5
Lambda Value: 7.75
Lambda Value: 8.0
Lambda Value: 8.25
Lambda Value: 8.5
Lambda Value: 8.75

,Hidden_Nodes,Activation,Lambda Value,avg_Accuracy_Seed_Mean,avg_Accuracy_Seed_Std,avg_Accuracy_Seed_Min,avg_Accuracy_Seed_Max,avg_Precision_Seed_Mean,avg_Precision_Seed_Std,avg_Precision_Seed_Min,...,avg_F1-Score_Seed_Min,avg_F1-Score_Seed_Max,avg_Balanced Accuracy_Seed_Mean,avg_Balanced Accuracy_Seed_Std,avg_Balanced Accuracy_Seed_Min,avg_Balanced Accuracy_Seed_Max,avg_MCC_Seed_Mean,avg_MCC_Seed_Std,avg_MCC_Seed_Min,avg_MCC_Seed_Max
0,40,sigmoid,7.00,0.6805,0.0313,0.6275,0.7490,0.7054,0.0413,0.6499,...,0.5994,0.7188,0.6799,0.0312,0.6258,0.7477,0.3662,0.0637,0.2622,0.5083
1,40,sigmoid,7.25,0.6810,0.0305,0.6314,0.7451,0.7059,0.0405,0.6499,...,0.6060,0.7177,0.6805,0.0304,0.6298,0.7438,0.3672,0.0622,0.2691,0.4992
2,40,sigmoid,7.50,0.6803,0.0312,0.6275,0.7451,0.7049,0.0414,0.6449,...,0.6003,0.7177,0.6797,0.0311,0.6260,0.7438,0.3657,0.0636,0.2614,0.4992
3,40,sigmoid,7.75,0.6814,0.0319,0.6314,0.7451,0.7063,0.0422,0.6449,...,0.6063,0.7177,0.6808,0.0317,0.6300,0.7438,0.3680,0.0650,0.2690,0.4992
4,40,sigmoid,8.00,0.6807,0.0320,0.6314,0.7412,0.7051,0.0421,0.6449,...,0.6063,0.7149,0.6801,0.0318,0.6300,0.7398,0.3664,0.0650,0.2690,0.4908
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,60,sigmoid,7.75,0.7027,0.0236,0.6549,0.7490,0.7310,0.0293,0.6853,...,0.6383,0.7208,0.7021,0.0235,0.6545,0.7477,0.4119,0.0465,0.3230,0.5134
164,60,sigmoid,8.00,0.7027,0.0238,0.6549,0.7490,0.7314,0.0296,0.6853,...,0.6383,0.7237,0.7021,0.0237,0.6545,0.7477,0.4119,0.0469,0.3230,0.5134
165,60,sigmoid,8.25,0.7033,0.0243,0.6549,0.7490,0.7332,0.0297,0.6853,...,0.6383,0.7268,0.7027,0.0242,0.6545,0.7477,0.4134,0.0478,0.3230,0.5143
166,60,sigmoid,8.50,0.7042,0.0255,0.6549,0.7529,0.7344,0.0306,0.6853,...,0.6383,0.7268,0.7036,0.0255,0.6545,0.7517,0.4154,0.0502,0.3230,0.5221
167,60,sigmoid,8.75,0.7049,0.0256,0.6549,0.7529,0.7355,0.0302,0.6853,...,0.6383,0.7268,0.7044,0.0255,0.6545,0.7517,0.4170,0.0503,0.3230,0.5221

In [ ]:
# # Extract the absolute best configuration from the granular Lambda Grid Search
# final_grids_df['Weighted_Score'] = (final_grids_df['avg_Accuracy_Seed_Mean'] * 0.5) + (final_grids_df['avg_MCC_Seed_Mean'] * 0.5)
# optimal_config = final_grids_df.sort_values(by='Weighted_Score', ascending=False).iloc[0]
#
# opt_hidden = int(optimal_config['Hidden_Nodes'])
# opt_lambda = float(optimal_config['Lambda Value'])
#
# print(f"Optimal Configuration Detected -> Hidden Nodes: {opt_hidden} | Lambda: {opt_lambda}")
#
# # Execute K-Fold split to obtain distinct train/val data for benchmarking
# from ABC_ELM import ABC_ELM
#
# splitter = DataSplit(random_state=42, test_size=0.2, k_fold=2)
# x_test, y_test, folds = splitter.k_fold_data_spiting(X, y)
#
# # We will demonstrate the metaheuristic optimization on Fold 0
# fold_0 = folds[0]
# x_train_f0 = fold_0['X_train_fold']
# y_train_f0 = fold_0['y_train_fold']
# x_val_f0   = fold_0['X_val_fold']
# y_val_f0   = fold_0['y_val_fold']
#
# print("\n[+] Initializing ABC(II)-ELM Optimization...")
# # Parameters SN=10, limit=10, iter_max=100 are derived directly from the literature
# abc_model = ABC_ELM(
#     feature_size=x_train_f0.shape[1],
#     hidden_size=opt_hidden,
#     activation_function=sigmoid,
#     regularization_lambda=opt_lambda,
#     SN=10, limit=15, iter_max=2500
# )
#
# # Fit the model (this will take longer due to the swarm search space)
# abc_model.fit(x_train_f0, y_train_f0)
#
# # Evaluate
# y_pred_abc = abc_model.predict(x_val_f0)
# eval_metrics = EvaluationMatrix(y_val_f0, y_pred_abc)
#
# print("\n=== ABC-ELM Optimization Results (Fold 0) ===")
# for metric, value in eval_metrics.get_all_metrics().items():
#     print(f"{metric}: {value:.4f}")