In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

from Pipeline.Algorithm.ArtificialBeeColonyElm import ArtificialBeeColonyElm
from Pipeline.Algorithm.ArtificialBeeColonyElmCVEnsemble import ArtificialBeeColonyElmCVEnsemble
from Pipeline.Algorithm.ExtremeLearningMachine import ExtremeLearningMachine
from Pipeline.Global.GallstoneDataSet import GallstoneDataSet
from Pipeline.Global.GlobalSetting import GlobalSetting
from Pipeline.Methodology.EvaluationMatrix import EvaluationMatrix

In [2]:
random_seed = 42
cv_test_count = 5

In [3]:
gallstone_dataset = GallstoneDataSet()
gallstone_dataset.fetch_data_path_0()
gallstone_dataset.cross_validate_test(cv_test_count)

In [4]:
model_configs = GlobalSetting.get_model_configs()

In [5]:
elm_config = next(cfg for cfg in model_configs if cfg["Model_Types"] == "Best_Hidden_Nodes")
elm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train, y_train, x_test, y_test = gallstone_dataset.fold_split[fold_idx]
    features_size = x_train.shape[1]
    scaler  = MinMaxScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled  = scaler.transform(x_test)
    elm = ExtremeLearningMachine(features_size=features_size,
                                 hidden_size=elm_config['Hidden_Nodes'],
                                 activation_function=elm_config['Activation'],
                                 regularization_lambda=elm_config['Lambda_Value'])
    elm.initialize_random_weights(scale=1.0, random_seed = 42)
    elm.fit(x_train_scaled,y_train)
    y_pred = elm.predict(x_test_scaled)
    evaluation = EvaluationMatrix(y_true=y_test,y_pred=y_pred)
    elm_fold_results.append(evaluation.get_all_metrics())
elm_final_result = pd.DataFrame(elm_fold_results)
elm_final_result.describe()

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.761855,0.790823,0.709476,0.745082,0.813447,0.744300,0.722329,0.761461,0.529284
std,0.033078,0.025221,0.095709,0.055471,0.045073,0.051384,0.079338,0.032822,0.058989
min,0.718750,0.758621,0.562500,0.666667,0.781250,0.666667,0.600000,0.718750,0.460566
25%,0.734375,0.781250,0.687500,0.714286,0.781250,0.721311,0.700637,0.734375,0.470824
50%,0.781250,0.781250,0.709677,0.756757,0.781250,0.758621,0.728477,0.779081,0.562500
75%,0.781250,0.814815,0.781250,0.781250,0.848485,0.781250,0.781250,0.781250,0.564827
max,0.793651,0.818182,0.806452,0.806452,0.875000,0.793651,0.801282,0.793851,0.587702

In [6]:
relm_config = next(cfg for cfg in model_configs if cfg["Model_Types"] == "Best_Lambda")
relm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train, y_train, x_test, y_test = gallstone_dataset.fold_split[fold_idx]
    features_size = x_train.shape[1]
    scaler  = MinMaxScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled  = scaler.transform(x_test)
    relm = ExtremeLearningMachine(features_size         = features_size,
                                  hidden_size           = relm_config['Hidden_Nodes'],
                                  activation_function   = relm_config['Activation'],
                                  regularization_lambda = relm_config['Lambda_Value'])
    relm.initialize_random_weights(scale=1.0, random_seed = 42)
    relm.fit(x_train_scaled,y_train)
    y_pred = relm.predict(x_test_scaled)
    evaluation_relm = EvaluationMatrix(y_true=y_test,y_pred=y_pred)
    relm_fold_results.append(evaluation_relm.get_all_metrics())
relm_final_result = pd.DataFrame(relm_fold_results)
relm_final_result.describe()

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.752579,0.767833,0.715726,0.742579,0.788826,0.739173,0.724577,0.752276,0.507454
std,0.044980,0.025951,0.090353,0.062302,0.025917,0.058229,0.078058,0.045245,0.087413
min,0.703125,0.750000,0.593750,0.666667,0.750000,0.666667,0.620915,0.703125,0.416333
25%,0.734375,0.750000,0.677419,0.722222,0.781250,0.711864,0.690789,0.732649,0.468747
50%,0.750000,0.760000,0.718750,0.735294,0.787879,0.741935,0.727848,0.750000,0.500000
75%,0.750000,0.766667,0.750000,0.750000,0.812500,0.750000,0.750000,0.750000,0.500979
max,0.825397,0.812500,0.838710,0.838710,0.812500,0.825397,0.833333,0.825605,0.651210

In [7]:
opt_relm_config = next(cfg for cfg in model_configs if cfg["Model_Types"] == "Grid_Optimization")
opt_relm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train, y_train, x_test, y_test = gallstone_dataset.fold_split[fold_idx]
    features_size = x_train.shape[1]
    scaler  = MinMaxScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled  = scaler.transform(x_test)
    opt_relm = ExtremeLearningMachine(features_size         = features_size,
                                      hidden_size           = opt_relm_config['Hidden_Nodes'],
                                      activation_function   = opt_relm_config['Activation'],
                                      regularization_lambda = opt_relm_config['Lambda_Value'])
    opt_relm.initialize_random_weights(scale=1.0, random_seed = 42)
    opt_relm.fit(x_train_scaled, y_train)
    y_pred = opt_relm.predict(x_test_scaled)
    evaluation_relm = EvaluationMatrix(y_true=y_test,y_pred=y_pred)
    opt_relm_fold_results.append(evaluation_relm.get_all_metrics())
opt_relm_final_result = pd.DataFrame(opt_relm_fold_results)
opt_relm_final_result.describe()

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.746379,0.769791,0.696573,0.734237,0.795265,0.727867,0.708071,0.745919,0.497832
std,0.089368,0.094573,0.134129,0.101399,0.083514,0.102564,0.120713,0.089734,0.179749
min,0.625000,0.642857,0.562500,0.611111,0.687500,0.600000,0.576923,0.625000,0.251976
25%,0.687500,0.703704,0.612903,0.675676,0.757576,0.655172,0.629139,0.685239,0.374903
50%,0.765625,0.794118,0.625000,0.707317,0.781250,0.727273,0.662252,0.765625,0.553596
75%,0.812500,0.838710,0.838710,0.833333,0.843750,0.818182,0.833333,0.812500,0.626224
max,0.841270,0.869565,0.843750,0.843750,0.906250,0.838710,0.838710,0.841230,0.682460

In [8]:
abc_elm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train, y_train, x_test, y_test = gallstone_dataset.fold_split[fold_idx]
    features_size = x_train.shape[1]
    scaler  = MinMaxScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled  = scaler.transform(x_test)
    abc_elm = ArtificialBeeColonyElm(features_size          = features_size,
                                     hidden_size            = elm_config['Hidden_Nodes'],
                                     activation_function    = elm_config['Activation'],
                                     regularization_lambda  = elm_config['Lambda_Value'],
                                     random_state           = random_seed,
                                     fitness_function       = GlobalSetting.evaluation_function,
                                     solution_size          = GlobalSetting.solution_size,
                                     trial_limit            = GlobalSetting.trial_limit,
                                     max_iteration          = GlobalSetting.max_iteration)
    abc_elm.fit(x_train_scaled, y_train)
    y_pred = abc_elm.predict(x_test_scaled)
    evaluation_abc_elm = EvaluationMatrix(y_true=y_test,y_pred=y_pred)
    abc_elm_fold_results.append(evaluation_abc_elm.get_all_metrics())

abc_elm_final_result = pd.DataFrame(abc_elm_fold_results)
abc_elm_final_result.describe()

Seed None  | Iteration 050 complete | Duration: 0.0536s | Scout Triggers: 1 | Best Fitness: 0.879415

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.755506,0.794562,0.677419,0.730237,0.832386,0.729003,0.696702,0.754903,0.517204
std,0.072853,0.060245,0.123118,0.083580,0.034967,0.093854,0.112168,0.072770,0.141713
min,0.640625,0.695652,0.500000,0.609756,0.781250,0.581818,0.529801,0.640625,0.293080
25%,0.761905,0.785714,0.656250,0.717949,0.818182,0.736842,0.686275,0.760585,0.529233
50%,0.765625,0.807692,0.677419,0.729730,0.843750,0.736842,0.700000,0.763930,0.531772
75%,0.765625,0.840000,0.709677,0.750000,0.843750,0.745763,0.723684,0.765625,0.544436
max,0.843750,0.843750,0.843750,0.843750,0.875000,0.843750,0.843750,0.843750,0.687500

In [9]:
abc_relm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train, y_train, x_test, y_test = gallstone_dataset.fold_split[fold_idx]
    features_size = x_train.shape[1]
    scaler  = MinMaxScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled  = scaler.transform(x_test)
    abc_relm = ArtificialBeeColonyElm(features_size          = features_size,
                                     hidden_size            = relm_config['Hidden_Nodes'],
                                     activation_function    = relm_config['Activation'],
                                     regularization_lambda  = relm_config['Lambda_Value'],
                                     random_state           = random_seed,
                                     fitness_function       = GlobalSetting.evaluation_function,
                                     solution_size          = GlobalSetting.solution_size,
                                     trial_limit            = GlobalSetting.trial_limit,
                                     max_iteration          = GlobalSetting.max_iteration)
    abc_relm.fit(x_train_scaled, y_train)
    y_pred = abc_relm.predict(x_test_scaled)
    evaluation_abc_relm = EvaluationMatrix(y_true=y_test,y_pred=y_pred)
    abc_relm_fold_results.append(evaluation_abc_relm.get_all_metrics())

abc_relm_final_result = pd.DataFrame(abc_relm_fold_results)
abc_relm_final_result.describe()

Seed None  | Iteration 050 complete | Duration: 0.0325s | Scout Triggers: 1 | Best Fitness: 0.868708

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.746081,0.792134,0.664718,0.719983,0.826326,0.718661,0.684547,0.745522,0.501329
std,0.038867,0.045841,0.099660,0.057428,0.050972,0.057059,0.083789,0.039269,0.073842
min,0.718750,0.740741,0.562500,0.674419,0.781250,0.678571,0.604027,0.716520,0.438211
25%,0.718750,0.758621,0.593750,0.675000,0.787879,0.679245,0.625000,0.718750,0.451848
50%,0.734375,0.791667,0.645161,0.702703,0.812500,0.689655,0.662252,0.734375,0.492419
75%,0.746032,0.812500,0.709677,0.735294,0.843750,0.733333,0.718954,0.745464,0.499169
max,0.812500,0.857143,0.812500,0.812500,0.906250,0.812500,0.812500,0.812500,0.625000

In [10]:
opt_abc_relm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train, y_train, x_test, y_test = gallstone_dataset.fold_split[fold_idx]
    features_size = x_train.shape[1]
    scaler  = MinMaxScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled  = scaler.transform(x_test)
    opt_abc_relm = ArtificialBeeColonyElm(features_size          = features_size,
                                     hidden_size            = opt_relm_config['Hidden_Nodes'],
                                     activation_function    = opt_relm_config['Activation'],
                                     regularization_lambda  = opt_relm_config['Lambda_Value'],
                                     random_state           = random_seed,
                                     fitness_function       = GlobalSetting.evaluation_function,
                                     solution_size          = GlobalSetting.solution_size,
                                     trial_limit            = GlobalSetting.trial_limit,
                                     max_iteration          = GlobalSetting.max_iteration)
    opt_abc_relm.fit(x_train_scaled, y_train)
    y_pred = opt_abc_relm.predict(x_test_scaled)
    evaluation_opt_abc_relm = EvaluationMatrix(y_true=y_test,y_pred=y_pred)
    opt_abc_relm_fold_results.append(evaluation_opt_abc_relm.get_all_metrics())

opt_abc_relm_final_result = pd.DataFrame(opt_abc_relm_fold_results)
opt_abc_relm_final_result.describe()

Seed None  | Iteration 050 complete | Duration: 0.0259s | Scout Triggers: 1 | Best Fitness: 0.863759

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.749306,0.784932,0.690323,0.733004,0.807386,0.728431,0.703995,0.748854,0.507503
std,0.058018,0.078747,0.118749,0.077269,0.081038,0.071618,0.099942,0.058013,0.116740
min,0.656250,0.678571,0.562500,0.638889,0.718750,0.633333,0.608108,0.656250,0.314970
25%,0.750000,0.774194,0.593750,0.681818,0.781250,0.692308,0.608974,0.747801,0.501519
50%,0.750000,0.777778,0.677419,0.729730,0.781250,0.724138,0.695364,0.750000,0.539360
75%,0.777778,0.794118,0.774194,0.781250,0.818182,0.774194,0.774194,0.777722,0.555444
max,0.812500,0.900000,0.843750,0.833333,0.937500,0.818182,0.833333,0.812500,0.626224

In [11]:
opt_abc_cv_en_relm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train, y_train, x_test, y_test = gallstone_dataset.fold_split[fold_idx]
    features_size = x_train.shape[1]
    opt_abc_cv_en_relm = ArtificialBeeColonyElmCVEnsemble(features_size          = features_size,
                                     hidden_size            = opt_relm_config['Hidden_Nodes'],
                                     activation_function    = opt_relm_config['Activation'],
                                     regularization_lambda  = opt_relm_config['Lambda_Value'],
                                     random_state           = random_seed,
                                     fitness_function       = GlobalSetting.evaluation_function,
                                     solution_size          = GlobalSetting.solution_size,
                                     trial_limit            = GlobalSetting.trial_limit,
                                     max_iteration          = GlobalSetting.max_iteration)
    opt_abc_cv_en_relm.fit(x_train, y_train)
    y_pred = opt_abc_cv_en_relm.predict(x_test)
    evaluation_opt_abc_cv_en_relm = EvaluationMatrix(y_true=y_test,y_pred=y_pred)
    opt_abc_cv_en_relm_fold_results.append(evaluation_opt_abc_cv_en_relm.get_all_metrics())

opt_abc_cv_en_relm_final_result = pd.DataFrame(opt_abc_cv_en_relm_fold_results)
opt_abc_cv_en_relm_final_result.describe()

Seed None  | Iteration 050 complete | Duration: 0.1165s | Scout Triggers: 2 | Best Fitness: 0.783476

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.758829,0.792620,0.697177,0.740292,0.819886,0.737538,0.711967,0.758532,0.524825
std,0.056167,0.052176,0.118418,0.077125,0.051239,0.074279,0.101440,0.056183,0.108644
min,0.671875,0.720000,0.562500,0.641026,0.781250,0.631579,0.588235,0.671875,0.352282
25%,0.750000,0.781250,0.593750,0.690476,0.781250,0.703704,0.633333,0.750000,0.526361
50%,0.765625,0.785714,0.709677,0.750000,0.812500,0.745763,0.723684,0.763930,0.531772
75%,0.781250,0.812500,0.781250,0.781250,0.818182,0.781250,0.781250,0.781250,0.562500
max,0.825397,0.863636,0.838710,0.838710,0.906250,0.825397,0.833333,0.825605,0.651210