In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

from Pipeline.Algorithm.ArtificialBeeColonyElm import ArtificialBeeColonyElm
from Pipeline.Algorithm.ArtificialBeeColonyElmCVEnsemble import ArtificialBeeColonyElmCVEnsemble
from Pipeline.Algorithm.ExtremeLearningMachine import ExtremeLearningMachine
from Pipeline.Global.GallstoneDataSet import GallstoneDataSet
from Pipeline.Global.GlobalSetting import GlobalSetting
from Pipeline.Methodology.EvaluationMatrix import EvaluationMatrix

In [2]:
random_seed = 42
cv_test_count = 5

In [3]:
gallstone_dataset = GallstoneDataSet()
gallstone_dataset.fetch_cleaned_data_path()
gallstone_dataset.cross_validate_split(cv_test_count)

In [4]:
model_configs = GlobalSetting.get_model_configs()

In [5]:
elm_config = next(cfg for cfg in model_configs if cfg["Model_Types"] == "Best_Hidden_Nodes")
elm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train_scaled, y_train, x_test_scaled, y_test = gallstone_dataset.scaled_fold_split[fold_idx]
    features_size = x_train_scaled.shape[1]

    elm = ExtremeLearningMachine(feature_size= features_size,
                                 hidden_size            = elm_config['Hidden_Nodes'],
                                 activation_function    = elm_config['Activation'],
                                 regularization_lambda  = elm_config['Lambda_Value'])
    elm.initialize_random_weights(scale = 1.0, random_seed = random_seed)

    elm.fit(x_train_scaled,y_train)
    y_pred = elm.predict(x_test_scaled)

    evaluation = EvaluationMatrix(y_true = y_test, y_pred = y_pred)
    elm_fold_results.append(evaluation.get_all_metrics())

elm_final_result = pd.DataFrame(elm_fold_results)
elm_final_result.describe()

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.761806,0.798157,0.696169,0.736263,0.826136,0.742496,0.713755,0.761153,0.528304
std,0.027406,0.029753,0.056818,0.036292,0.035220,0.034614,0.047997,0.027132,0.053018
min,0.734375,0.758621,0.625000,0.692308,0.781250,0.701754,0.653595,0.734375,0.470824
25%,0.734375,0.785714,0.677419,0.714286,0.812500,0.721311,0.700637,0.734375,0.480384
50%,0.765625,0.800000,0.687500,0.736842,0.818182,0.745763,0.704698,0.763930,0.531772
75%,0.777778,0.806452,0.709677,0.750000,0.843750,0.750000,0.723684,0.776210,0.564499
max,0.796875,0.840000,0.781250,0.787879,0.875000,0.793651,0.786164,0.796875,0.594040

In [6]:
relm_config = next(cfg for cfg in model_configs if cfg["Model_Types"] == "Best_Lambda")
relm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train_scaled, y_train, x_test_scaled, y_test = gallstone_dataset.scaled_fold_split[fold_idx]
    features_size = x_train_scaled.shape[1]

    relm = ExtremeLearningMachine(feature_size= features_size,
                                  hidden_size           = relm_config['Hidden_Nodes'],
                                  activation_function   = relm_config['Activation'],
                                  regularization_lambda = relm_config['Lambda_Value'])
    relm.initialize_random_weights(scale = 1.0, random_seed = random_seed)

    relm.fit(x_train_scaled,y_train)
    y_pred = relm.predict(x_test_scaled)

    evaluation_relm = EvaluationMatrix(y_true = y_test, y_pred = y_pred)
    relm_fold_results.append(evaluation_relm.get_all_metrics())

relm_final_result = pd.DataFrame(relm_fold_results)
relm_final_result.describe()

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.777579,0.824156,0.708871,0.750324,0.844508,0.758250,0.727094,0.776689,0.563716
std,0.039611,0.066991,0.081480,0.048819,0.076951,0.045901,0.066330,0.039676,0.080568
min,0.718750,0.733333,0.625000,0.705882,0.750000,0.709677,0.666667,0.718750,0.438357
25%,0.765625,0.787879,0.645161,0.714286,0.781250,0.727273,0.675676,0.761975,0.540868
50%,0.781250,0.833333,0.687500,0.725000,0.875000,0.740741,0.696203,0.781250,0.592157
75%,0.796875,0.857143,0.774194,0.800000,0.878788,0.800000,0.789474,0.796875,0.594040
max,0.825397,0.909091,0.812500,0.806452,0.937500,0.813559,0.807453,0.824597,0.653156

In [7]:
opt_relm_config = next(cfg for cfg in model_configs if cfg["Model_Types"] == "Grid_Optimization")
opt_relm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train_scaled, y_train, x_test_scaled, y_test = gallstone_dataset.scaled_fold_split[fold_idx]
    features_size = x_train_scaled.shape[1]

    opt_relm = ExtremeLearningMachine(feature_size= features_size,
                                      hidden_size           = opt_relm_config['Hidden_Nodes'],
                                      activation_function   = opt_relm_config['Activation'],
                                      regularization_lambda = opt_relm_config['Lambda_Value'])
    opt_relm.initialize_random_weights(scale = 1.0, random_seed = random_seed)

    opt_relm.fit(x_train_scaled, y_train)
    y_pred = opt_relm.predict(x_test_scaled)

    evaluation_relm = EvaluationMatrix(y_true = y_test, y_pred = y_pred)
    opt_relm_fold_results.append(evaluation_relm.get_all_metrics())

opt_relm_final_result = pd.DataFrame(opt_relm_fold_results)
opt_relm_final_result.describe()

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.755804,0.812399,0.664718,0.721943,0.844508,0.728526,0.688303,0.754613,0.521587
std,0.066901,0.091078,0.092538,0.062627,0.085943,0.077488,0.084585,0.066332,0.136630
min,0.671875,0.720000,0.562500,0.641026,0.750000,0.631579,0.588235,0.671875,0.352282
25%,0.734375,0.757576,0.612903,0.692308,0.781250,0.701754,0.646259,0.734375,0.480384
50%,0.750000,0.800000,0.625000,0.707317,0.843750,0.703704,0.653595,0.745846,0.512123
75%,0.765625,0.826087,0.741935,0.774194,0.878788,0.769231,0.776398,0.765625,0.531510
max,0.857143,0.958333,0.781250,0.794872,0.968750,0.836364,0.777027,0.855343,0.731636

In [8]:
abc_elm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train_scaled, y_train, x_test_scaled, y_test = gallstone_dataset.scaled_fold_split[fold_idx]
    features_size = x_train_scaled.shape[1]

    abc_elm = ArtificialBeeColonyElm(feature_size           = features_size,
                                     hidden_size            = elm_config['Hidden_Nodes'],
                                     activation_function    = elm_config['Activation'],
                                     regularization_lambda  = elm_config['Lambda_Value'],
                                     random_state           = random_seed,
                                     fitness_function       = GlobalSetting.evaluation_function,
                                     solution_size          = 50, #GlobalSetting.solution_size,
                                     trial_limit            = 15, #GlobalSetting.trial_limit,
                                     max_iteration          = 80) #GlobalSetting.max_iteration)

    abc_elm.fit(x_train_scaled, y_train)
    y_pred = abc_elm.predict(x_test_scaled)

    evaluation_abc_elm = EvaluationMatrix(y_true = y_test, y_pred = y_pred)
    abc_elm_fold_results.append(evaluation_abc_elm.get_all_metrics())

abc_elm_final_result = pd.DataFrame(abc_elm_fold_results)
abc_elm_final_result.describe()

Seed 42  | Iteration 080 complete | Duration: 0.2737s | Scout Triggers: 3 | Best Fitness: 0.9058403

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.755605,0.793608,0.690121,0.729351,0.820076,0.736962,0.707870,0.755098,0.516509
std,0.051917,0.072014,0.054359,0.046454,0.073830,0.051871,0.051430,0.051554,0.106133
min,0.687500,0.700000,0.625000,0.676471,0.718750,0.677419,0.649351,0.687500,0.375735
25%,0.718750,0.766667,0.656250,0.684211,0.787879,0.689655,0.664557,0.718750,0.445399
50%,0.765625,0.769231,0.677419,0.743590,0.812500,0.754098,0.709459,0.764907,0.530593
75%,0.793651,0.857143,0.741935,0.764706,0.875000,0.763636,0.746753,0.791835,0.600876
max,0.812500,0.875000,0.750000,0.777778,0.906250,0.800000,0.769231,0.812500,0.629941

In [9]:
abc_relm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train, y_train, x_test, y_test = gallstone_dataset.fold_split[fold_idx]
    features_size = x_train.shape[1]
    scaler  = MinMaxScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled  = scaler.transform(x_test)
    abc_relm = ArtificialBeeColonyElm(feature_size= features_size,
                                      hidden_size            = relm_config['Hidden_Nodes'],
                                      activation_function    = relm_config['Activation'],
                                      regularization_lambda  = relm_config['Lambda_Value'],
                                      random_state           = random_seed,
                                      fitness_function       = GlobalSetting.evaluation_function,
                                      solution_size          = 80,#GlobalSetting.solution_size,
                                      trial_limit            = 50,# GlobalSetting.trial_limit,
                                      max_iteration          = 100)#GlobalSetting.max_iteration)
    abc_relm.fit(x_train_scaled, y_train)
    y_pred = abc_relm.predict(x_test_scaled)
    evaluation_abc_relm = EvaluationMatrix(y_true=y_test,y_pred=y_pred)
    abc_relm_fold_results.append(evaluation_abc_relm.get_all_metrics())

abc_relm_final_result = pd.DataFrame(abc_relm_fold_results)
abc_relm_final_result.describe()

Seed 42  | Iteration 100 complete | Duration: 0.1759s | Scout Triggers: 0 | Best Fitness: 0.883909

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.780704,0.835479,0.696371,0.743956,0.863258,0.758615,0.719813,0.779814,0.569415
std,0.032190,0.046327,0.046181,0.031930,0.047672,0.035070,0.040737,0.031750,0.065280
min,0.734375,0.777778,0.656250,0.702703,0.812500,0.711864,0.677419,0.734375,0.474579
25%,0.781250,0.800000,0.656250,0.725000,0.812500,0.750000,0.690789,0.778104,0.563602
50%,0.781250,0.840000,0.677419,0.743590,0.878788,0.750000,0.704698,0.781250,0.569734
75%,0.781250,0.875000,0.741935,0.764706,0.906250,0.774194,0.759494,0.781250,0.580948
max,0.825397,0.884615,0.750000,0.783784,0.906250,0.807018,0.766667,0.824093,0.658215

In [7]:
opt_abc_relm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train, y_train, x_test, y_test = gallstone_dataset.fold_split[fold_idx]
    features_size = x_train.shape[1]
    scaler  = MinMaxScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled  = scaler.transform(x_test)
    opt_abc_relm = ArtificialBeeColonyElm(feature_size= features_size,
                                          hidden_size            = elm_config['Hidden_Nodes'],
                                          activation_function    = elm_config['Activation'],
                                          regularization_lambda  = elm_config['Lambda_Value'],
                                          random_state           = random_seed,
                                          fitness_function       = GlobalSetting.evaluation_function,
                                          solution_size          = GlobalSetting.solution_size,
                                          trial_limit            = GlobalSetting.trial_limit,
                                          max_iteration          = GlobalSetting.max_iteration)
    opt_abc_relm.fit(x_train_scaled, y_train)
    y_pred = opt_abc_relm.predict(x_test_scaled)
    evaluation_opt_abc_relm = EvaluationMatrix(y_true=y_test,y_pred=y_pred)
    opt_abc_relm_fold_results.append(evaluation_opt_abc_relm.get_all_metrics())

opt_abc_relm_final_result = pd.DataFrame(opt_abc_relm_fold_results)
opt_abc_relm_final_result.describe()

Seed 42  | Iteration 020 complete | Duration: 0.0416s | Scout Triggers: 1 | Best Fitness: 0.894794

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.768204,0.819593,0.683468,0.733167,0.850947,0.744723,0.706598,0.767207,0.543484
std,0.054964,0.068904,0.062998,0.049737,0.060025,0.060481,0.061290,0.054776,0.111821
min,0.718750,0.750000,0.625000,0.684211,0.781250,0.689655,0.649351,0.718750,0.440959
25%,0.718750,0.769231,0.645161,0.694444,0.812500,0.700000,0.671141,0.718750,0.445399
50%,0.750000,0.800000,0.656250,0.717949,0.848485,0.714286,0.673077,0.746823,0.505651
75%,0.825397,0.862069,0.709677,0.769231,0.875000,0.800000,0.743243,0.823589,0.659153
max,0.828125,0.916667,0.781250,0.800000,0.937500,0.819672,0.796178,0.828125,0.666256

In [8]:
opt_abc_cv_en_relm_fold_results = []
for fold_idx in range(cv_test_count):
    x_train, y_train, x_test, y_test = gallstone_dataset.fold_split[fold_idx]
    features_size = x_train.shape[1]
    opt_abc_cv_en_relm = ArtificialBeeColonyElmCVEnsemble(feature_size          = features_size,
                                     hidden_size            = elm_config['Hidden_Nodes'],
                                     activation_function    = relm_config['Activation'],
                                     regularization_lambda  = elm_config['Lambda_Value'],
                                     random_state           = random_seed,
                                     fitness_function       = GlobalSetting.evaluation_function,
                                     solution_size          = 80,#GlobalSetting.solution_size,
                                     trial_limit            = 50,#GlobalSetting.trial_limit,
                                     max_iteration          = 100)#GlobalSetting.max_iteration)
    opt_abc_cv_en_relm.fit(x_train, y_train)
    y_pred = opt_abc_cv_en_relm.predict(x_test)
    evaluation_opt_abc_cv_en_relm = EvaluationMatrix(y_true=y_test,y_pred=y_pred)
    opt_abc_cv_en_relm_fold_results.append(evaluation_opt_abc_cv_en_relm.get_all_metrics())

opt_abc_cv_en_relm_final_result = pd.DataFrame(opt_abc_cv_en_relm_fold_results)
opt_abc_cv_en_relm_final_result.describe()

Seed 42  | Iteration 100 complete | Duration: 1.0597s | Scout Triggers: 0 | Best Fitness: 0.819122

,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.749157,0.782962,0.689718,0.730741,0.807576,0.728898,0.704074,0.748647,0.505289
std,0.027729,0.044697,0.092853,0.049622,0.059491,0.045494,0.075309,0.027955,0.052225
min,0.730159,0.741935,0.562500,0.674419,0.750000,0.679245,0.604027,0.728831,0.464743
25%,0.734375,0.758621,0.645161,0.702703,0.781250,0.701754,0.666667,0.734375,0.468979
50%,0.734375,0.769231,0.709677,0.727273,0.787879,0.730159,0.718954,0.734375,0.499169
75%,0.750000,0.787879,0.718750,0.742857,0.812500,0.733333,0.723270,0.748778,0.499513
max,0.796875,0.857143,0.812500,0.806452,0.906250,0.800000,0.807453,0.796875,0.594040