In [1]:
import json
import os

import numpy as np

from Pipeline.Model.EvaluationMatrix import EvaluationMatrix
from Pipeline.Model.GallstoneDataSet import GallstoneDataSet
from Pipeline.Model.EvaluationELM import EvaluationELM
from Pipeline.Model.ExtremeLearningMachine import sigmoid

In [2]:
record_dir = '../../Dataset/Record/'
os.makedirs(record_dir, exist_ok=True)

In [3]:
gallstone_dataset = GallstoneDataSet()
gallstone_dataset.fetch_data_path_1()
features_size = gallstone_dataset.x_train_scaled.shape[1]

In [4]:
hidden_size_explore = range(55, 59)
lambda_value_explore = 2.0 ** np.arange(-20, -10)

In [5]:
# 1. Instantiate the Evaluator Object ONCE
evaluator = EvaluationELM(
    x=gallstone_dataset.x_train,
    y=gallstone_dataset.y_train,
    activation_function=sigmoid,
    elm_initial_state_range= range(41, 45),
    data_split_state_range= range(1, 4),
    test_size=0.2,
    k_fold=5
)

In [6]:
hidden_size_record ,hidden_size_result = evaluator.grid_search_hidden_size(hidden_size_explore)

In [7]:
hidden_size_record.to_csv(os.path.join(record_dir, 'hidden_size_record.csv'), index=False)

In [8]:
hidden_node_list = EvaluationELM.extract_top_results(hidden_size_result)
best_hidden_size = hidden_node_list.iloc[0]
best_hidden_size

Hidden_Nodes                       58
Activation                    sigmoid
Lambda_Value                      0.0
avg_Accuracy_Seed_Mean         0.7307
avg_Accuracy_Seed_Std          0.0217
avg_Accuracy_Seed_SEM          0.0125
avg_Accuracy_Seed_Min          0.5294
avg_Accuracy_Seed_Max          0.8627
avg_Precision_Seed_Mean        0.7536
avg_Precision_Seed_Std         0.0286
avg_Precision_Seed_SEM         0.0165
avg_Precision_Seed_Min           0.52
avg_Precision_Seed_Max           0.95
avg_Recall_Seed_Mean           0.6818
avg_Recall_Seed_Std            0.0211
avg_Recall_Seed_SEM            0.0122
avg_Recall_Seed_Min              0.36
avg_Recall_Seed_Max            0.8462
avg_NPV_Seed_Mean              0.7203
avg_NPV_Seed_Std               0.0195
avg_NPV_Seed_SEM               0.0112
avg_NPV_Seed_Min               0.5385
avg_NPV_Seed_Max               0.8462
avg_Specificity_Seed_Mean      0.7777
avg_Specificity_Seed_Std       0.0307
avg_Specificity_Seed_SEM       0.0177
avg_Specificity_Seed_Min       0.5385
avg_Specificity_Seed_Max       0.9615
avg_F1-Score_Seed_Mean         0.7106
avg_F1-Score_Seed_Std          0.0212
avg_F1-Score_Seed_SEM          0.0123
avg_F1-Score_Seed_Min          0.4737
avg_F1-Score_Seed_Max          0.8444
avg_F2-Score_Seed_Mean         0.6921
avg_F2-Score_Seed_Std          0.0211
avg_F2-Score_Seed_SEM          0.0122
avg_F2-Score_Seed_Min          0.3982
avg_F2-Score_Seed_Max            0.84
avg_Bal Accuracy_Seed_Mean     0.7298
avg_Bal Accuracy_Seed_Std      0.0216
avg_Bal Accuracy_Seed_SEM      0.0125
avg_Bal Accuracy_Seed_Min      0.5292
avg_Bal Accuracy_Seed_Max      0.8608
avg_MCC_Seed_Mean              0.4665
avg_MCC_Seed_Std               0.0447
avg_MCC_Seed_SEM               0.0258
avg_MCC_Seed_Min               0.0585
avg_MCC_Seed_Max               0.7388
rank_score                     0.6799
Name: 3, dtype: object

In [9]:
lambda_record, lambda_result = evaluator.grid_search_lambda(
    hidden_size=best_hidden_size['Hidden_Nodes'],
    lambda_range=lambda_value_explore
)

In [10]:
lambda_record.to_csv(os.path.join(record_dir, 'lambda_record.csv'), index=False)

In [11]:
lambda_value_list = EvaluationELM.extract_top_results(lambda_result)
best_lambda_value = lambda_value_list.iloc[0]
best_lambda_value

Hidden_Nodes                        58
Activation                     sigmoid
Lambda_Value                  0.000244
avg_Accuracy_Seed_Mean          0.7343
avg_Accuracy_Seed_Std           0.0198
avg_Accuracy_Seed_SEM           0.0114
avg_Accuracy_Seed_Min            0.549
avg_Accuracy_Seed_Max           0.8627
avg_Precision_Seed_Mean         0.7567
avg_Precision_Seed_Std          0.0265
avg_Precision_Seed_SEM          0.0153
avg_Precision_Seed_Min          0.5417
avg_Precision_Seed_Max            0.95
avg_Recall_Seed_Mean            0.6858
avg_Recall_Seed_Std             0.0208
avg_Recall_Seed_SEM              0.012
avg_Recall_Seed_Min               0.36
avg_Recall_Seed_Max               0.88
avg_NPV_Seed_Mean                0.724
avg_NPV_Seed_Std                0.0179
avg_NPV_Seed_SEM                0.0103
avg_NPV_Seed_Min                0.5556
avg_NPV_Seed_Max                0.8696
avg_Specificity_Seed_Mean        0.781
avg_Specificity_Seed_Std        0.0286
avg_Specificity_Seed_SEM        0.0165
avg_Specificity_Seed_Min        0.5769
avg_Specificity_Seed_Max        0.9615
avg_F1-Score_Seed_Mean          0.7144
avg_F1-Score_Seed_Std           0.0198
avg_F1-Score_Seed_SEM           0.0114
avg_F1-Score_Seed_Min           0.4737
avg_F1-Score_Seed_Max           0.8571
avg_F2-Score_Seed_Mean           0.696
avg_F2-Score_Seed_Std           0.0204
avg_F2-Score_Seed_SEM           0.0118
avg_F2-Score_Seed_Min           0.3982
avg_F2-Score_Seed_Max           0.8594
avg_Bal Accuracy_Seed_Mean      0.7334
avg_Bal Accuracy_Seed_Std       0.0197
avg_Bal Accuracy_Seed_SEM       0.0114
avg_Bal Accuracy_Seed_Min       0.5485
avg_Bal Accuracy_Seed_Max       0.8623
avg_MCC_Seed_Mean               0.4735
avg_MCC_Seed_Std                0.0408
avg_MCC_Seed_SEM                0.0236
avg_MCC_Seed_Min                0.0971
avg_MCC_Seed_Max                0.7388
rank_score                      0.6842
Name: 8, dtype: object

In [12]:
lambda_result

,Hidden_Nodes,Activation,Lambda_Value,avg_Accuracy_Seed_Mean,avg_Accuracy_Seed_Std,avg_Accuracy_Seed_SEM,avg_Accuracy_Seed_Min,avg_Accuracy_Seed_Max,avg_Precision_Seed_Mean,avg_Precision_Seed_Std,...,avg_Bal Accuracy_Seed_Mean,avg_Bal Accuracy_Seed_Std,avg_Bal Accuracy_Seed_SEM,avg_Bal Accuracy_Seed_Min,avg_Bal Accuracy_Seed_Max,avg_MCC_Seed_Mean,avg_MCC_Seed_Std,avg_MCC_Seed_SEM,avg_MCC_Seed_Min,avg_MCC_Seed_Max
0,58,sigmoid,9.536743e-07,0.7307,0.0217,0.0125,0.5294,0.8627,0.7536,0.0286,...,0.7298,0.0216,0.0125,0.5292,0.8608,0.4665,0.0447,0.0258,0.0585,0.7388
1,58,sigmoid,1.907349e-06,0.7307,0.0217,0.0125,0.5294,0.8627,0.7536,0.0286,...,0.7298,0.0216,0.0125,0.5292,0.8608,0.4665,0.0447,0.0258,0.0585,0.7388
2,58,sigmoid,3.814697e-06,0.7307,0.0217,0.0125,0.5294,0.8627,0.7536,0.0286,...,0.7298,0.0216,0.0125,0.5292,0.8608,0.4665,0.0447,0.0258,0.0585,0.7388
3,58,sigmoid,7.629395e-06,0.7307,0.0217,0.0125,0.5294,0.8627,0.7536,0.0286,...,0.7298,0.0216,0.0125,0.5292,0.8608,0.4665,0.0447,0.0258,0.0585,0.7388
4,58,sigmoid,1.525879e-05,0.7304,0.0223,0.0129,0.5294,0.8627,0.7535,0.0288,...,0.7294,0.0222,0.0128,0.5292,0.8608,0.4659,0.0458,0.0265,0.0585,0.7388
5,58,sigmoid,3.051758e-05,0.7304,0.0223,0.0129,0.5294,0.8627,0.7535,0.0288,...,0.7294,0.0222,0.0128,0.5292,0.8608,0.4659,0.0458,0.0265,0.0585,0.7388
6,58,sigmoid,6.103516e-05,0.7304,0.0223,0.0129,0.5294,0.8627,0.7535,0.0288,...,0.7294,0.0222,0.0128,0.5292,0.8608,0.4659,0.0458,0.0265,0.0585,0.7388
7,58,sigmoid,1.220703e-04,0.7314,0.0214,0.0123,0.5294,0.8627,0.7546,0.0274,...,0.7304,0.0213,0.0123,0.5292,0.8608,0.4679,0.0441,0.0254,0.0585,0.7388
8,58,sigmoid,2.441406e-04,0.7343,0.0198,0.0114,0.5490,0.8627,0.7567,0.0265,...,0.7334,0.0197,0.0114,0.5485,0.8623,0.4735,0.0408,0.0236,0.0971,0.7388
9,58,sigmoid,4.882812e-04,0.7346,0.0214,0.0123,0.5490,0.8824,0.7567,0.0272,...,0.7337,0.0213,0.0123,0.5485,0.8808,0.4740,0.0435,0.0251,0.0971,0.7735

In [13]:
size_lambda_record , size_lambda_result = evaluator.grid_search_hidden_size_and_lambda(
    hidden_size_range=hidden_node_list['Hidden_Nodes'],
    lambda_range=lambda_value_explore
)

In [14]:
size_lambda_record.to_csv(os.path.join(record_dir, 'size_lambda_record.csv'), index=False)

In [15]:
size_lambda_list = EvaluationELM.extract_top_results(size_lambda_result)
best_size_lambda = size_lambda_list.iloc[0]
best_size_lambda

Hidden_Nodes                        58
Activation                     sigmoid
Lambda_Value                  0.000244
avg_Accuracy_Seed_Mean          0.7343
avg_Accuracy_Seed_Std           0.0198
avg_Accuracy_Seed_SEM           0.0114
avg_Accuracy_Seed_Min            0.549
avg_Accuracy_Seed_Max           0.8627
avg_Precision_Seed_Mean         0.7567
avg_Precision_Seed_Std          0.0265
avg_Precision_Seed_SEM          0.0153
avg_Precision_Seed_Min          0.5417
avg_Precision_Seed_Max            0.95
avg_Recall_Seed_Mean            0.6858
avg_Recall_Seed_Std             0.0208
avg_Recall_Seed_SEM              0.012
avg_Recall_Seed_Min               0.36
avg_Recall_Seed_Max               0.88
avg_NPV_Seed_Mean                0.724
avg_NPV_Seed_Std                0.0179
avg_NPV_Seed_SEM                0.0103
avg_NPV_Seed_Min                0.5556
avg_NPV_Seed_Max                0.8696
avg_Specificity_Seed_Mean        0.781
avg_Specificity_Seed_Std        0.0286
avg_Specificity_Seed_SEM        0.0165
avg_Specificity_Seed_Min        0.5769
avg_Specificity_Seed_Max        0.9615
avg_F1-Score_Seed_Mean          0.7144
avg_F1-Score_Seed_Std           0.0198
avg_F1-Score_Seed_SEM           0.0114
avg_F1-Score_Seed_Min           0.4737
avg_F1-Score_Seed_Max           0.8571
avg_F2-Score_Seed_Mean           0.696
avg_F2-Score_Seed_Std           0.0204
avg_F2-Score_Seed_SEM           0.0118
avg_F2-Score_Seed_Min           0.3982
avg_F2-Score_Seed_Max           0.8594
avg_Bal Accuracy_Seed_Mean      0.7334
avg_Bal Accuracy_Seed_Std       0.0197
avg_Bal Accuracy_Seed_SEM       0.0114
avg_Bal Accuracy_Seed_Min       0.5485
avg_Bal Accuracy_Seed_Max       0.8623
avg_MCC_Seed_Mean               0.4735
avg_MCC_Seed_Std                0.0408
avg_MCC_Seed_SEM                0.0236
avg_MCC_Seed_Min                0.0971
avg_MCC_Seed_Max                0.7388
rank_score                      0.6842
Name: 8, dtype: object

In [16]:
model_configs_payload = [
    {
        "Model_Types" : "Best_Hidden_Nodes",
        "Hidden_Nodes": int(best_hidden_size['Hidden_Nodes']),
        "Activation": "sigmoid",
        "Lambda_Value": float(best_hidden_size['Lambda_Value'])
    },
    {
        "Model_Types" : "Best_Lambda",
        "Hidden_Nodes": int(best_lambda_value['Hidden_Nodes']),
        "Activation": "sigmoid",
        "Lambda_Value": float(best_lambda_value['Lambda_Value'])
    },
    {
        "Model_Types" : "Best_Size_and_Lambda",
        "Hidden_Nodes": int(best_size_lambda['Hidden_Nodes']),
        "Activation": "sigmoid",
        "Lambda_Value": float(best_size_lambda['Lambda_Value'])
    }
]

In [17]:
dataset_dir = '../../Dataset/JSON/'
config_file = os.path.join(dataset_dir, 'full_model_configs.json')

with open(config_file, 'w') as f:
    json.dump(model_configs_payload, f, indent=4)

print(f"Successfully initialized {config_file} with {len(model_configs_payload)} configurations.")

Successfully initialized ../../Dataset/JSON/full_model_configs.json with 3 configurations.

In [18]:
lambda_record_elm_seed_eval = EvaluationMatrix.elm_seed_evaluation(lambda_record)
lambda_record_data_seed_eval = EvaluationMatrix.data_seed_evaluation(lambda_record)

In [21]:
lambda_record_elm_seed_eval

,Hidden_Nodes,Activation,Lambda_Value,Accuracy_Pooled_ELM_Seed_Std,Precision_Pooled_ELM_Seed_Std,Recall_Pooled_ELM_Seed_Std,NPV_Pooled_ELM_Seed_Std,Specificity_Pooled_ELM_Seed_Std,F1-Score_Pooled_ELM_Seed_Std,F2-Score_Pooled_ELM_Seed_Std,Bal Accuracy_Pooled_ELM_Seed_Std,MCC_Pooled_ELM_Seed_Std
0,58,sigmoid,9.536743e-07,0.0521,0.0652,0.0649,0.0465,0.0731,0.0577,0.0608,0.0521,0.1050
1,58,sigmoid,1.907349e-06,0.0521,0.0652,0.0649,0.0465,0.0731,0.0577,0.0608,0.0521,0.1050
2,58,sigmoid,3.814697e-06,0.0521,0.0652,0.0649,0.0465,0.0731,0.0577,0.0608,0.0521,0.1050
3,58,sigmoid,7.629395e-06,0.0521,0.0652,0.0649,0.0465,0.0731,0.0577,0.0608,0.0521,0.1050
4,58,sigmoid,1.525879e-05,0.0513,0.0650,0.0641,0.0454,0.0731,0.0570,0.0600,0.0514,0.1035
5,58,sigmoid,3.051758e-05,0.0513,0.0650,0.0641,0.0454,0.0731,0.0570,0.0600,0.0514,0.1035
6,58,sigmoid,6.103516e-05,0.0513,0.0650,0.0641,0.0454,0.0731,0.0570,0.0600,0.0514,0.1035
7,58,sigmoid,1.220703e-04,0.0510,0.0641,0.0650,0.0462,0.0711,0.0571,0.0607,0.0511,0.1030
8,58,sigmoid,2.441406e-04,0.0508,0.0622,0.0667,0.0474,0.0688,0.0571,0.0618,0.0509,0.1023
9,58,sigmoid,4.882812e-04,0.0516,0.0623,0.0691,0.0494,0.0685,0.0582,0.0637,0.0517,0.1039

In [22]:
elm_data_seed_var = lambda_record_elm_seed_eval['F2-Score_Pooled_ELM_Seed_Std'] / lambda_record_data_seed_eval['F2-Score_Pooled_Data_Seed_Std']
elm_data_seed_var

0    0.553734
1    0.553734
2    0.553734
3    0.553734
4    0.549451
5    0.549451
6    0.549451
7    0.552320
8    0.557762
9    0.576471
dtype: float64