In [1]:
import pandas as pd
from scipy import stats

In [2]:
df_ABC_RELM_ENSEMBLE_CD = pd.read_csv("ABC_CVEnsemble_RELMCD_Results.csv")
df_ABC_RELM_ENSEMBLE = pd.read_csv("ABC_CVEnsemble_RELM_Results.csv")
df_RELM_ENSEMBLE_CD = pd.read_csv("Grid_Optimization_CV_EnsembleCD_Results.csv")
df_RELM_ENSEMBLE = pd.read_csv("Grid_Optimization_CV_Ensemble_Results.csv")
df_RELM_CD = pd.read_csv("Grid_OptimizationCD_Results.csv")
df_RELM = pd.read_csv("Grid_Optimization_Results.csv")

In [3]:
df_RELM.describe()

,Hidden_Nodes,Lambda_Value,Fold_ID,Seed,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,150.0,150.000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,34.0,0.125,2.000000,115.500000,0.740589,0.779946,0.667594,0.717829,0.811944,0.715378,0.685185,0.739769,0.488443
std,0.0,0.000,1.418951,8.684438,0.055831,0.063438,0.099289,0.062129,0.067800,0.070537,0.087723,0.056042,0.110294
min,34.0,0.125,0.000000,101.000000,0.640625,0.645161,0.406250,0.604167,0.656250,0.541667,0.451389,0.640625,0.281387
25%,34.0,0.125,1.000000,108.000000,0.703125,0.730769,0.593750,0.666667,0.751894,0.666667,0.616883,0.703125,0.406449
50%,34.0,0.125,2.000000,115.500000,0.734375,0.774194,0.666835,0.705882,0.812500,0.709677,0.682524,0.734375,0.487500
75%,34.0,0.125,3.000000,123.000000,0.780382,0.826087,0.750000,0.762024,0.875000,0.769231,0.754717,0.779222,0.562455
max,34.0,0.125,4.000000,130.000000,0.888889,0.925926,0.870968,0.878788,0.937500,0.885246,0.876623,0.888609,0.778002

In [4]:
df_RELM_ENSEMBLE.describe()

,Hidden_Nodes,Lambda_Value,Fold_ID,Seed,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,150.0,150.000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,34.0,0.125,2.000000,115.500000,0.737325,0.778814,0.660477,0.713858,0.812468,0.710559,0.678866,0.736473,0.482572
std,0.0,0.000,1.418951,8.684438,0.055130,0.065927,0.099729,0.061982,0.068105,0.070333,0.087785,0.055412,0.109820
min,34.0,0.125,0.000000,101.000000,0.625000,0.653846,0.437500,0.605263,0.656250,0.560000,0.479452,0.625000,0.254514
25%,34.0,0.125,1.000000,108.000000,0.687500,0.727273,0.580645,0.668605,0.750000,0.655172,0.612245,0.687500,0.394771
50%,34.0,0.125,2.000000,115.500000,0.734375,0.772727,0.656250,0.694444,0.812500,0.703818,0.668790,0.734375,0.468979
75%,34.0,0.125,3.000000,123.000000,0.777778,0.826087,0.741935,0.757576,0.875000,0.761905,0.744490,0.776714,0.563326
max,34.0,0.125,4.000000,130.000000,0.857143,0.947368,0.875000,0.866667,0.968750,0.852459,0.859873,0.856855,0.722705

In [5]:
df_ABC_RELM_ENSEMBLE.describe()

,Hidden_Nodes,Lambda_Value,Fold_ID,Seed,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,150.0,150.000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,34.0,0.125,2.000000,115.500000,0.752740,0.797027,0.678347,0.728639,0.825726,0.727648,0.696344,0.752036,0.514534
std,0.0,0.000,1.418951,8.684438,0.060008,0.070825,0.107524,0.067991,0.073204,0.075491,0.094892,0.060088,0.117981
min,34.0,0.125,0.000000,101.000000,0.593750,0.607143,0.406250,0.583333,0.656250,0.541667,0.451389,0.593750,0.188982
25%,34.0,0.125,1.000000,108.000000,0.703125,0.740741,0.593750,0.675676,0.757576,0.677556,0.625000,0.703125,0.437678
50%,34.0,0.125,2.000000,115.500000,0.750000,0.784161,0.677419,0.716518,0.818182,0.721311,0.698420,0.750000,0.500000
75%,34.0,0.125,3.000000,123.000000,0.796875,0.862069,0.774194,0.783784,0.899384,0.787630,0.775847,0.796703,0.594040
max,34.0,0.125,4.000000,130.000000,0.904762,0.944444,0.903226,0.906250,0.968750,0.903226,0.903226,0.904738,0.809476

In [6]:
df_RELM_CD.describe()

,Hidden_Nodes,Lambda_Value,Fold_ID,Seed,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,150.0,150.000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,34.0,0.125,2.000000,115.500000,0.781062,0.823528,0.711579,0.752412,0.848655,0.761825,0.730547,0.780117,0.567984
std,0.0,0.000,1.418951,8.684438,0.050091,0.063284,0.066993,0.048583,0.061290,0.056068,0.061709,0.050079,0.100873
min,34.0,0.125,0.000000,101.000000,0.666667,0.677419,0.516129,0.634146,0.687500,0.603774,0.547945,0.664315,0.335761
25%,34.0,0.125,1.000000,108.000000,0.746032,0.777778,0.656250,0.717949,0.812500,0.724922,0.687120,0.745181,0.493814
50%,34.0,0.125,2.000000,115.500000,0.781250,0.827586,0.709677,0.750000,0.846117,0.760263,0.728477,0.781250,0.566947
75%,34.0,0.125,3.000000,123.000000,0.812500,0.869565,0.774194,0.789474,0.906250,0.800000,0.781250,0.812500,0.633817
max,34.0,0.125,4.000000,130.000000,0.890625,0.960000,0.843750,0.857143,0.968750,0.885246,0.859873,0.890625,0.784706

In [7]:
df_RELM_ENSEMBLE_CD.describe()

,Hidden_Nodes,Lambda_Value,Fold_ID,Seed,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,150.0,150.000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,34.0,0.125,2.000000,115.500000,0.785412,0.833753,0.709368,0.753366,0.859394,0.764871,0.730253,0.784381,0.577816
std,0.0,0.000,1.418951,8.684438,0.050128,0.064928,0.067318,0.047911,0.061236,0.056870,0.062174,0.050084,0.101213
min,34.0,0.125,0.000000,101.000000,0.650794,0.680000,0.516129,0.631579,0.656250,0.603774,0.547945,0.649194,0.304912
25%,34.0,0.125,1.000000,108.000000,0.750000,0.785714,0.661542,0.722222,0.812500,0.727273,0.692709,0.750000,0.507064
50%,34.0,0.125,2.000000,115.500000,0.793651,0.840000,0.709677,0.756757,0.875000,0.771930,0.736688,0.792339,0.593724
75%,34.0,0.125,3.000000,123.000000,0.812500,0.880000,0.750000,0.789075,0.906250,0.800000,0.775847,0.812500,0.636285
max,34.0,0.125,4.000000,130.000000,0.906250,0.964286,0.870968,0.882353,0.969697,0.900000,0.876623,0.906250,0.818923

In [8]:
df_ABC_RELM_ENSEMBLE_CD.describe()

,Hidden_Nodes,Lambda_Value,Fold_ID,Seed,Accuracy,Precision,Recall,NPV,Specificity,F1-Score,F2-Score,Bal Accuracy,MCC
count,150.0,150.000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,34.0,0.125,2.000000,115.500000,0.789678,0.842356,0.708730,0.754906,0.868453,0.768306,0.731132,0.788592,0.587090
std,0.0,0.000,1.418951,8.684438,0.049206,0.063888,0.066107,0.047464,0.057262,0.056274,0.061252,0.049143,0.099650
min,34.0,0.125,0.000000,101.000000,0.666667,0.692308,0.548387,0.641026,0.718750,0.618182,0.574324,0.664819,0.335761
25%,34.0,0.125,1.000000,108.000000,0.752976,0.793103,0.656250,0.721948,0.820312,0.736842,0.681818,0.752520,0.518640
50%,34.0,0.125,2.000000,115.500000,0.796875,0.846154,0.714214,0.756757,0.875000,0.777778,0.738255,0.795210,0.594797
75%,34.0,0.125,3.000000,123.000000,0.825397,0.887821,0.750000,0.786855,0.906250,0.811924,0.774194,0.824975,0.658918
max,34.0,0.125,4.000000,130.000000,0.890625,0.962963,0.870968,0.866667,0.969697,0.881356,0.859873,0.890625,0.790965

In [9]:
import pandas as pd
from scipy import stats

def compare_model_distributions(df_model_a, df_model_b, name_a="Model_A", name_b="Model_B", metric='MCC'):
    """
    Evaluates if Model B improves efficacy and stability compared to Model A
    across independent initialization seeds.

    Parameters:
    - df_model_a: DataFrame containing results for the baseline/control model.
    - df_model_b: DataFrame containing results for the experimental model.
    - name_a (str): Human-readable name for Model A (e.g., 'RELM_CD').
    - name_b (str): Human-readable name for Model B (e.g., 'RELM_ENSEMBLE_CD').
    - metric (str): The performance metric to evaluate (default: 'MCC').
    """

    # 1. Aggregate by Seed (Collapsing the CV overlap)
    agg_a = df_model_a.groupby('Seed')[metric].mean().reset_index()
    agg_b = df_model_b.groupby('Seed')[metric].mean().reset_index()

    # Ensure perfectly matched pairs by merging on Seed dynamically
    merged = pd.merge(agg_a, agg_b, on='Seed', suffixes=(f'_{name_a}', f'_{name_b}'))
    data_a = merged[f'{metric}_{name_a}']
    data_b = merged[f'{metric}_{name_b}']

    print(f"--- Descriptive Statistics ({metric}) ---")
    print(f"{name_a:<20} -> Mean: {data_a.mean():.4f}, Std Dev: {data_a.std():.4f}")
    print(f"{name_b:<20} -> Mean: {data_b.mean():.4f}, Std Dev: {data_b.std():.4f}\n")

    # 2. Test Dimension 1: Efficacy (Wilcoxon Signed-Rank)
    # H0: The median difference between the paired samples is zero.
    stat_w, p_val_w = stats.wilcoxon(data_a, data_b)
    print("--- Test 1: Efficacy (Wilcoxon Signed-Rank) ---")
    if p_val_w < 0.05:
        # Determine the direction of the empirical shift
        better_model = name_b if data_b.mean() > data_a.mean() else name_a
        print(f"Result: SIGNIFICANT (p = {p_val_w:.4e}).")
        print(f"Conclusion: {better_model} systematically shifts performance higher.")
    else:
        print(f"Result: NOT Significant (p = {p_val_w:.4e}).")
        print(f"Conclusion: No statistically significant difference in central tendency.")

    # 3. Test Dimension 2: Stability / Robustness to Initialization (Levene's Test)
    # H0: The population variances are equal.
    stat_l, p_val_l = stats.levene(data_a, data_b)
    print("\n--- Test 2: Stability (Levene's Test) ---")
    if p_val_l < 0.05:
        print(f"Result: SIGNIFICANT (p = {p_val_l:.4e}).")
        if data_b.std() < data_a.std():
            print(f"Conclusion: {name_b} successfully compresses variance compared to {name_a}.")
        else:
            print(f"Conclusion: {name_b} INCREASES variance (Less stable than {name_a}).")
    else:
        print(f"Result: NOT Significant (p = {p_val_l:.4e}).")
        print(f"Conclusion: No significant difference in initialization variance between {name_a} and {name_b}.")

In [10]:
compare_model_distributions(
    df_model_a=df_RELM_CD,
    df_model_b=df_RELM_ENSEMBLE_CD,
    name_a='RELM_CD',
    name_b='Ensemble_RELM_CD',
    metric='MCC'
)

--- Descriptive Statistics (MCC) ---
RELM_CD              -> Mean: 0.5680, Std Dev: 0.0427
Ensemble_RELM_CD     -> Mean: 0.5778, Std Dev: 0.0283

--- Test 1: Efficacy (Wilcoxon Signed-Rank) ---
Result: NOT Significant (p = 4.0449e-01).
Conclusion: No statistically significant difference in central tendency.

--- Test 2: Stability (Levene's Test) ---
Result: NOT Significant (p = 2.6480e-01).
Conclusion: No significant difference in initialization variance between RELM_CD and Ensemble_RELM_CD.

In [11]:
compare_model_distributions(
    df_model_a=df_RELM_ENSEMBLE_CD,
    df_model_b=df_ABC_RELM_ENSEMBLE_CD,
    name_a='Ensemble_RELM_CD',
    name_b='ABC_Ensemble_RELM_CD',
    metric='MCC'
)

--- Descriptive Statistics (MCC) ---
Ensemble_RELM_CD     -> Mean: 0.5778, Std Dev: 0.0283
ABC_Ensemble_RELM_CD -> Mean: 0.5871, Std Dev: 0.0215

--- Test 1: Efficacy (Wilcoxon Signed-Rank) ---
Result: NOT Significant (p = 1.2935e-01).
Conclusion: No statistically significant difference in central tendency.

--- Test 2: Stability (Levene's Test) ---
Result: NOT Significant (p = 1.4434e-01).
Conclusion: No significant difference in initialization variance between Ensemble_RELM_CD and ABC_Ensemble_RELM_CD.

In [12]:
compare_model_distributions(
    df_model_a=df_RELM_CD,
    df_model_b=df_ABC_RELM_ENSEMBLE_CD,
    name_a='Baseline_RELM_CD',
    name_b='Proposed_Architecture',
    metric='MCC'
)

--- Descriptive Statistics (MCC) ---
Baseline_RELM_CD     -> Mean: 0.5680, Std Dev: 0.0427
Proposed_Architecture -> Mean: 0.5871, Std Dev: 0.0215

--- Test 1: Efficacy (Wilcoxon Signed-Rank) ---
Result: SIGNIFICANT (p = 4.9710e-02).
Conclusion: Proposed_Architecture systematically shifts performance higher.

--- Test 2: Stability (Levene's Test) ---
Result: SIGNIFICANT (p = 4.4287e-02).
Conclusion: Proposed_Architecture successfully compresses variance compared to Baseline_RELM_CD.

In [13]:
compare_model_distributions(
    df_model_a=df_RELM,
    df_model_b=df_RELM_ENSEMBLE,
    name_a='RELM',
    name_b='Ensemble_RELM',
    metric='MCC'
)

--- Descriptive Statistics (MCC) ---
RELM                 -> Mean: 0.4884, Std Dev: 0.0425
Ensemble_RELM        -> Mean: 0.4826, Std Dev: 0.0359

--- Test 1: Efficacy (Wilcoxon Signed-Rank) ---
Result: NOT Significant (p = 5.2911e-01).
Conclusion: No statistically significant difference in central tendency.

--- Test 2: Stability (Levene's Test) ---
Result: NOT Significant (p = 3.0730e-01).
Conclusion: No significant difference in initialization variance between RELM and Ensemble_RELM.

In [14]:
compare_model_distributions(
    df_model_a=df_RELM_ENSEMBLE,
    df_model_b=df_ABC_RELM_ENSEMBLE,
    name_a='Ensemble_RELM',
    name_b='ABC_Ensemble_RELM',
    metric='MCC'
)

--- Descriptive Statistics (MCC) ---
Ensemble_RELM        -> Mean: 0.4826, Std Dev: 0.0359
ABC_Ensemble_RELM    -> Mean: 0.5145, Std Dev: 0.0319

--- Test 1: Efficacy (Wilcoxon Signed-Rank) ---
Result: SIGNIFICANT (p = 2.0202e-03).
Conclusion: ABC_Ensemble_RELM systematically shifts performance higher.

--- Test 2: Stability (Levene's Test) ---
Result: NOT Significant (p = 7.6333e-01).
Conclusion: No significant difference in initialization variance between Ensemble_RELM and ABC_Ensemble_RELM.

In [15]:
compare_model_distributions(
    df_model_a=df_RELM,
    df_model_b=df_ABC_RELM_ENSEMBLE,
    name_a='Baseline_RELM',
    name_b='Proposed_Architecture',
    metric='MCC'
)

--- Descriptive Statistics (MCC) ---
Baseline_RELM        -> Mean: 0.4884, Std Dev: 0.0425
Proposed_Architecture -> Mean: 0.5145, Std Dev: 0.0319

--- Test 1: Efficacy (Wilcoxon Signed-Rank) ---
Result: SIGNIFICANT (p = 2.2099e-02).
Conclusion: Proposed_Architecture systematically shifts performance higher.

--- Test 2: Stability (Levene's Test) ---
Result: NOT Significant (p = 1.5990e-01).
Conclusion: No significant difference in initialization variance between Baseline_RELM and Proposed_Architecture.