In [1]:
from Pipeline.Global.GlobalSetting import GlobalSetting
from Pipeline.Methodology.EvaluationABCELM import EvaluationABCELM
from Pipeline.Global.GallstoneDataSet import GallstoneDataSet

In [2]:
gallstone_dataset = GallstoneDataSet()
gallstone_dataset.fetch_data_path_1()

features_size = gallstone_dataset.x_train.shape[1]
x_train = gallstone_dataset.x_train
x_test = gallstone_dataset.x_test
y_train = gallstone_dataset.y_train

In [3]:
evaluationABC = EvaluationABCELM(x_train=x_train,y_train=y_train,activation_function=GlobalSetting.sigmoid)
raw_results, agg_results = evaluationABC.abc_parameter_explore(
        hidden_size=10,
        lambda_value=0.0
    )

Max Iter: 10 | Trial: 5 | Size: 5 | Seed: 188
Max Iter: 10 | Trial: 5 | Size: 5 | Seed: 189
Max Iter: 10 | Trial: 5 | Size: 5 | Seed: 190
Max Iter: 10 | Trial: 5 | Size: 10 | Seed: 188
Max Iter: 10 | Trial: 5 | Size: 10 | Seed: 189
Max Iter: 10 | Trial: 5 | Size: 10 | Seed: 190
Max Iter: 10 | Trial: 10 | Size: 5 | Seed: 188
Max Iter: 10 | Trial: 10 | Size: 5 | Seed: 189
Max Iter: 10 | Trial: 10 | Size: 5 | Seed: 190
Max Iter: 10 | Trial: 10 | Size: 10 | Seed: 188
Max Iter: 10 | Trial: 10 | Size: 10 | Seed: 189
Max Iter: 10 | Trial: 10 | Size: 10 | Seed: 190
Max Iter: 20 | Trial: 5 | Size: 5 | Seed: 188
Max Iter: 20 | Trial: 5 | Size: 5 | Seed: 189
Max Iter: 20 | Trial: 5 | Size: 5 | Seed: 190
Max Iter: 20 | Trial: 5 | Size: 10 | Seed: 188
Max Iter: 20 | Trial: 5 | Size: 10 | Seed: 189
Max Iter: 20 | Trial: 5 | Size: 10 | Seed: 190
Max Iter: 20 | Trial: 10 | Size: 5 | Seed: 188
Max Iter: 20 | Trial: 10 | Size: 5 | Seed: 189
Max Iter: 20 | Trial: 10 | Size: 5 | Seed: 190
Max Iter: 20 | Trial: 10 | Size: 10 | Seed: 188
Max Iter: 20 | Trial: 10 | Size: 10 | Seed: 189
Max Iter: 20 | Trial: 10 | Size: 10 | Seed: 190

In [4]:
raw_results

    max_iter  trial_limit  solution_size  seed  best_fitness
0         10            5              5   188      0.674493
1         10            5              5   189      0.664164
2         10            5              5   190      0.660864
3         10            5             10   188      0.656295
4         10            5             10   189      0.673864
5         10            5             10   190      0.699356
6         10           10              5   188      0.667795
7         10           10              5   189      0.682374
8         10           10              5   190      0.615882
9         10           10             10   188      0.676221
10        10           10             10   189      0.683955
11        10           10             10   190      0.692419
12        20            5              5   188      0.655677
13        20            5              5   189      0.674656
14        20            5              5   190      0.686549
15        20            5             10   188      0.676117
16        20            5             10   189      0.701737
17        20            5             10   190      0.681812
18        20           10              5   188      0.683012
19        20           10              5   189      0.650635
20        20           10              5   190      0.647012
21        20           10             10   188      0.683071
22        20           10             10   189      0.687400
23        20           10             10   190      0.681238

In [5]:
agg_results

,max_iter,trial_limit,solution_size,avg_best_fitness_Seed_Mean,avg_best_fitness_Seed_Std,avg_best_fitness_Seed_Min,avg_best_fitness_Seed_Max,avg_best_fitness_Seed_SEM
0,10,5,5,0.666507,0.007110,0.660864,0.674493,0.004105
1,10,5,10,0.676505,0.021652,0.656295,0.699356,0.012501
2,10,10,5,0.655350,0.034949,0.615882,0.682374,0.020178
3,10,10,10,0.684198,0.008102,0.676221,0.692419,0.004677
4,20,5,5,0.672294,0.015571,0.655677,0.686549,0.008990
5,20,5,10,0.686555,0.013452,0.676117,0.701737,0.007767
6,20,10,5,0.660220,0.019822,0.647012,0.683012,0.011444
7,20,10,10,0.683903,0.003164,0.681238,0.687400,0.001827

In [6]:
agg_results['LCB'] = agg_results['avg_best_fitness_Seed_Mean'] - agg_results['avg_best_fitness_Seed_SEM']
agg_results

,max_iter,trial_limit,solution_size,avg_best_fitness_Seed_Mean,avg_best_fitness_Seed_Std,avg_best_fitness_Seed_Min,avg_best_fitness_Seed_Max,avg_best_fitness_Seed_SEM,LCB
0,10,5,5,0.666507,0.007110,0.660864,0.674493,0.004105,0.662402
1,10,5,10,0.676505,0.021652,0.656295,0.699356,0.012501,0.664004
2,10,10,5,0.655350,0.034949,0.615882,0.682374,0.020178,0.635173
3,10,10,10,0.684198,0.008102,0.676221,0.692419,0.004677,0.679521
4,20,5,5,0.672294,0.015571,0.655677,0.686549,0.008990,0.663304
5,20,5,10,0.686555,0.013452,0.676117,0.701737,0.007767,0.678789
6,20,10,5,0.660220,0.019822,0.647012,0.683012,0.011444,0.648776
7,20,10,10,0.683903,0.003164,0.681238,0.687400,0.001827,0.682077

In [8]:
l = EvaluationABCELM.extract_top_results(agg_results)
l

,max_iter,trial_limit,solution_size,avg_best_fitness_Seed_Mean,avg_best_fitness_Seed_Std,avg_best_fitness_Seed_Min,avg_best_fitness_Seed_Max,avg_best_fitness_Seed_SEM,LCB,rank_score
7,20,10,10,0.683903,0.003164,0.681238,0.687400,0.001827,0.682077,0.682077
3,10,10,10,0.684198,0.008102,0.676221,0.692419,0.004677,0.679521,0.679521
5,20,5,10,0.686555,0.013452,0.676117,0.701737,0.007767,0.678789,0.678789
1,10,5,10,0.676505,0.021652,0.656295,0.699356,0.012501,0.664004,0.664004
4,20,5,5,0.672294,0.015571,0.655677,0.686549,0.008990,0.663304,0.663304