In [1]:
from Pipeline.Global.Plotting import Plotting
from Pipeline.Methodology import ABC_Testing

In [2]:
all_trace_record, result_summary = ABC_Testing.lcb_trace_evaluation("../Trace History")

In [3]:
summary_for_evaluation = result_summary.drop(columns=['expr_name','metric_name','scout_avg','scout_std','train_MCC_LCB_Mean','train_MCC_LCB_std','train_MCC_LCB_sem','train_MCC_trace_floor'])

In [4]:
summary_for_evaluation

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
0,100,50,100,0.553075,0.039233,0.007163,0.534594
1,100,50,120,0.558257,0.042923,0.007837,0.538039
2,100,50,150,0.549223,0.051754,0.009449,0.524845
3,100,50,250,0.563736,0.031232,0.005702,0.549024
4,10,5,1000,0.572297,0.042456,0.007751,0.552299
5,10,5,100,0.539884,0.045809,0.008364,0.518306
6,10,5,120,0.542387,0.037018,0.006759,0.524950
7,10,5,150,0.542631,0.046954,0.008573,0.520514
8,10,5,250,0.554071,0.048507,0.008856,0.531222
9,10,5,500,0.552622,0.038720,0.007069,0.534383
10,10,5,50,0.556381,0.055405,0.010116,0.530283
11,10,5,750,0.547614,0.033694,0.006152,0.531743
12,20,10,1000,0.545969,0.035129,0.006414,0.529421
13,20,10,100,0.541231,0.036547,0.006673,0.524016
14,20,10,120,0.542075,0.047324,0.008640,0.519784
15,20,10,150,0.550613,0.043377,0.007920,0.530180
16,20,10,250,0.536902,0.039235,0.007163,0.518421
17,20,10,500,0.560179,0.041189,0.007520,0.540777
18,20,10,50,0.544400,0.050594,0.009237,0.520568
19,20,10,750,0.558026,0.044404,0.008107,0.537110
20,50,25,100,0.541734,0.052455,0.009577,0.517025
21,50,25,120,0.548238,0.048647,0.008882,0.525323
22,50,25,150,0.548370,0.048750,0.008900,0.525407
23,50,25,250,0.553856,0.047051,0.008590,0.531693
24,80,40,100,0.559428,0.053418,0.009753,0.534266
25,80,40,120,0.566198,0.049307,0.009002,0.542973
26,80,40,150,0.543911,0.051392,0.009383,0.519703
27,80,40,250,0.555777,0.039965,0.007297,0.536952

In [5]:
summary_for_evaluation[summary_for_evaluation['Solution_Size'] == 10].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
4,10,5,1000,0.572297,0.042456,0.007751,0.552299
9,10,5,500,0.552622,0.038720,0.007069,0.534383
11,10,5,750,0.547614,0.033694,0.006152,0.531743
8,10,5,250,0.554071,0.048507,0.008856,0.531222
10,10,5,50,0.556381,0.055405,0.010116,0.530283
6,10,5,120,0.542387,0.037018,0.006759,0.524950
7,10,5,150,0.542631,0.046954,0.008573,0.520514
5,10,5,100,0.539884,0.045809,0.008364,0.518306

In [6]:
summary_for_evaluation[summary_for_evaluation['Solution_Size'] == 20].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
17,20,10,500,0.560179,0.041189,0.007520,0.540777
19,20,10,750,0.558026,0.044404,0.008107,0.537110
15,20,10,150,0.550613,0.043377,0.007920,0.530180
12,20,10,1000,0.545969,0.035129,0.006414,0.529421
13,20,10,100,0.541231,0.036547,0.006673,0.524016
18,20,10,50,0.544400,0.050594,0.009237,0.520568
14,20,10,120,0.542075,0.047324,0.008640,0.519784
16,20,10,250,0.536902,0.039235,0.007163,0.518421

In [7]:
summary_for_evaluation[summary_for_evaluation['Solution_Size'] == 50].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
23,50,25,250,0.553856,0.047051,0.008590,0.531693
22,50,25,150,0.548370,0.048750,0.008900,0.525407
21,50,25,120,0.548238,0.048647,0.008882,0.525323
20,50,25,100,0.541734,0.052455,0.009577,0.517025

In [8]:
summary_for_evaluation[summary_for_evaluation['Solution_Size'] == 80].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
25,80,40,120,0.566198,0.049307,0.009002,0.542973
27,80,40,250,0.555777,0.039965,0.007297,0.536952
24,80,40,100,0.559428,0.053418,0.009753,0.534266
26,80,40,150,0.543911,0.051392,0.009383,0.519703

In [9]:
summary_for_evaluation[summary_for_evaluation['Solution_Size'] == 100].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
3,100,50,250,0.563736,0.031232,0.005702,0.549024
1,100,50,120,0.558257,0.042923,0.007837,0.538039
0,100,50,100,0.553075,0.039233,0.007163,0.534594
2,100,50,150,0.549223,0.051754,0.009449,0.524845

In [10]:
summary_for_evaluation[summary_for_evaluation['Max_Iteration'] == 100].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
0,100,50,100,0.553075,0.039233,0.007163,0.534594
24,80,40,100,0.559428,0.053418,0.009753,0.534266
13,20,10,100,0.541231,0.036547,0.006673,0.524016
5,10,5,100,0.539884,0.045809,0.008364,0.518306
20,50,25,100,0.541734,0.052455,0.009577,0.517025

In [11]:
summary_for_evaluation[summary_for_evaluation['Max_Iteration'] == 120].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
25,80,40,120,0.566198,0.049307,0.009002,0.542973
1,100,50,120,0.558257,0.042923,0.007837,0.538039
21,50,25,120,0.548238,0.048647,0.008882,0.525323
6,10,5,120,0.542387,0.037018,0.006759,0.524950
14,20,10,120,0.542075,0.047324,0.008640,0.519784

In [12]:
summary_for_evaluation[summary_for_evaluation['Max_Iteration'] == 150].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
15,20,10,150,0.550613,0.043377,0.007920,0.530180
22,50,25,150,0.548370,0.048750,0.008900,0.525407
2,100,50,150,0.549223,0.051754,0.009449,0.524845
7,10,5,150,0.542631,0.046954,0.008573,0.520514
26,80,40,150,0.543911,0.051392,0.009383,0.519703

In [13]:
summary_for_evaluation[summary_for_evaluation['Max_Iteration'] == 250].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
3,100,50,250,0.563736,0.031232,0.005702,0.549024
27,80,40,250,0.555777,0.039965,0.007297,0.536952
23,50,25,250,0.553856,0.047051,0.008590,0.531693
8,10,5,250,0.554071,0.048507,0.008856,0.531222
16,20,10,250,0.536902,0.039235,0.007163,0.518421

In [14]:
summary_for_evaluation[summary_for_evaluation['Max_Iteration'] == 500].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
17,20,10,500,0.560179,0.041189,0.007520,0.540777
9,10,5,500,0.552622,0.038720,0.007069,0.534383

In [15]:
summary_for_evaluation[summary_for_evaluation['Max_Iteration'] == 750].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
19,20,10,750,0.558026,0.044404,0.008107,0.537110
11,10,5,750,0.547614,0.033694,0.006152,0.531743

In [16]:
summary_for_evaluation[summary_for_evaluation['Max_Iteration'] == 1000].sort_values(['val_MCC_trace_floor'],ascending=False)

,Solution_Size,Trial_Limit,Max_Iteration,val_MCC_LCB_Mean,val_MCC_LCB_std,val_MCC_LCB_sem,val_MCC_trace_floor
4,10,5,1000,0.572297,0.042456,0.007751,0.552299
12,20,10,1000,0.545969,0.035129,0.006414,0.529421

In [17]:
# for i in all_trace_record:
#     Plotting.plot_rigorous_convergence(i)